### ISSUE TITLE
wrong answer related to Arrays of Int/Real (Bugzilla #835)

### ISSUE THREAD

**Issue by mpreiner** [CVC4/CVC4#1048]
**Imported from Bugzilla**
Reporter: *Andrew Reynolds*
Status: *NEW*
Severity: *major*
Assigned to: *Clark Barrett*
Component: *Arrays*
Milestone: *---*
Version: *master*
Platform: *PC*
OS: *Windows*

Original attachment names and IDs:
- _[test.smt2](http://cvc4.cs.stanford.edu/bugzilla_attachments/460_test.smt2)_ (wrong answer on this benchmark, ID 460)

On 2017-07-26 09:04:23 -0700, Andrew Reynolds wrote:
> Created attachment 460
> wrong answer on this benchmark
> 
> Current master CVC4 incorrectly answers "sat" on the attached benchmark with model:
> 
> (model
> (define\-fun a () (Array Int Int) (store ((as const (Array Int Int)) 0) 0 (/ 1 2)))
> (define\-fun b () (Array Int Real) (store ((as const (Array Int Int)) 0) 0 (/ 1 2)))
> (define\-fun c () (Array Int Int) ((as const (Array Int Int)) 0))
> )
> 
> Here, the model for a is not (Array Int Int).
> 
> As discussed, we should consider adding is\-T( a ) predicates for each type T that belong to the owner of T.
> 
> In the short term, perhaps we need to make the Array solver setIncomplete for cases like this.
> 
> \-Andy

**Comment by ajreynol** [comment]
Regarding this bug, my impression is that implementing the is-T( a ) predicates for each type T is not worth the trouble.  This increases the burden on the theory solvers and the core of CVC4, and doesn't add that much functionality to the users (I don't recall many users who are interested in problems that involve subtypes beyond Int/Real). 

My proposal is the following:
(1) Leave the typing rules in computeType(...) methods the same.  This means for instance that t1 = t2 still internally type checks for terms t1 and t2 that have comparable type.  
(2) To catch input constraints that are non-standard, we have a stricter type check that occurs once for each literal that is asserted to TheoryEngine.  By non-standard, I mean we reject (= t1 t2) for t1:T1 and t2:T2 if T1 != T2 and { T1, T2 } != { Int, Real }. In other words, we still allow mixed Int/Real equalities (since they are handled by TheoryArith) but reject all others.  This "stricter check" would also need to be done for other literals like set membership.


The justification for (1) is that we still want to allow equalities between terms of different types, for instance, when checking models. Take this example:

(declare-fun x () (Set Real))
(declare-fun y () (Set Real))
(assert (member 0.5 x))
(assert (member 0 y))
(assert (not (= x y)))
(check-sat)

Here, we find a model where
x -> (singleton 0.5)
y -> (singleton 0)

After substitution, the last constraint becomes:
(not (= (singleton 0.5) (singleton 0)))
where we have an equality between (Set Real) and (Set Int).  We do not want to reject this (internally generated) equality.


My thought is that we only need to reject equalities between terms of different types that enter into TheoryEngine. 

If we agree with the above proposal, the question I have is where is to add the stricter type check method?  TheoryEngine::preRegister?

**Comment by ajreynol** [comment]
This was fixed by pull request #1098 
We now throw a type exception for the benchmark.
