### ISSUE TITLE
Add CVC4_OVERRIDE macro

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#1277]
See [this](https://github.com/CVC4/CVC4/pull/1249#issuecomment-337090440) comment.

**Comment by timothy-king** [comment]
After looking into this, a better solution that seems to work is to add the following to a common ".swig" or ".i" file once:
```
#if SWIG_VERSION < 0x030000
%define override %enddef
#endif
```
The same can be done for `final`. Documentation on [SWIG_VERSION](http://www.swig.org/Doc3.0/SWIGDocumentation.html#Preface_nn9 ). AFAICT, we want SWIG version 3.0 (hence 0x030000).

**Comment by 4tXJ7f** [comment]
Not a huge fan of redefining keywords of the language but that would certainly be an option. Also, we should make sure that whatever solution we choose is consistent with how we deal with [`thread_local`](https://github.com/CVC4/CVC4/blob/master/src/base/tls.h#L23-L29).

**Comment by timothy-king** [comment]
What is I find appealing about this is that:

1. The C++ code gets be agnostic. We can then use `override` everywhere instead of `CVC4_OVERRIDE` in cvc4_public.h headers. This is more readable.
2. No extra public header for the #ifdef that implements the roughly the same thing:
```
// base/override.h
#include "cvc4_public.h"
#if SWIG_VERSION < 0x030000
#define CVC4_OVERRIDE
#else
#define CVC4_OVERRIDE override
#endif
```
3. The burden of getting this right is pushed onto the SWIG side, which kind of makes sense.

**Comment by timothy-king** [comment]
> Also, we should make sure that whatever solution we choose is consistent with how we deal with thread_local.

This is a bit different as it changes the underlying C++ types.

**Comment by 4tXJ7f** [comment]
Hmm, that is a good point. I guess, I can live with this then.
