### ISSUE TITLE
[SyGuS] Unknown for a simple LIA problem

### ISSUE THREAD

**Issue by iwob** [CVC4/CVC4#1319]
I got the unknown answer for the following problem. Is this a bug, or rather a certain kind of fundamental problem?
```
(set-logic LIA)
(synth-fun mult12345 ((x Int)) Int)
(declare-var x Int)
(constraint (> (mult12345 x) (* x 12344)))
(constraint (< (mult12345 x) (* x 12346)))
(check-synth)
```

**Comment by ajreynol** [comment]
Actually, this conjecture is infeasible, since for x < 0, there is no value strictly between x*12344 and x*12346.

Often, an answer of "unknown" for SyGuS problems corresponds to CVC4 figuring out there are definitely no solutions.

I've opened a separate issue (#1320) for CVC4 to report back information when a synthesis conjecture is infeasible, something along the lines of:

sat
; The synthesis conjecture is infeasible for the value:
(define-fun x () Int -1)

**Comment by iwob** [comment]
You are right. Reporting infeasibility will certainly decrease the number of reported issues. :) Especially, when more users start to use this tool. Sorry for the trouble.
