### ISSUE TITLE
Our regressions w.r.t. CBQI

### ISSUE THREAD

**Issue by florianschanda** [CVC4/CVC4#1396]
Hi Andrew,

I promised some further updates on the CBQI / --no-cbqi front. Below is a list of benchmarks from https://github.com/florianschanda/smtlib_schanda that perform worse when not using --no-cbqi.

We have a large list of regressions in our testsuite, but a lot of that is due to everything running with --rlimit. However, I figured I would start by giving you a list of all VCs that were either:
* solved with --no-cbqi, and not solved now
* solved with --no-cbqi, still solved but taking at least 2x the time
* unknown with --no-cbqi, and now timing out / error

Let me know if you would like additional information. The timeout, btw, is set at 1 minute. In addition the CVC4 used was Martin's float branch, so I have only included the results that do not involve floating point in some way.

# Regressions in spark_2014_all (all previously solved/unknown)
[unknown ->  timeout ] spark_2014_all/AUFDTLIRA/patience___patience.adb_79_22_assert.smt2
[ solved -> 2x slower] spark_2014_all/AUFDTLIRA/red_black_trees___red_black_trees.adb_258_28_red_black_trees.adb_471_16_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P114-046__invariant___inrange1.ads_18_14_postcondition.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P114-046__invariant___inrange2.ads_18_14_postcondition.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P114-046__invariant___inrange3.ads_18_14_postcondition.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P114-046__invariant___inrange6.ads_18_14_postcondition.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_50_22_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_55_20_x86.adb_99_7_loop_invariant_preserv.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_60_28_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_66_19_x86.adb_99_7_loop_invariant_preserv.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_75_37_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_79_22_x86.adb_99_7_loop_invariant_preserv.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_82_19_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_83_31_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_87_31_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.adb_92_28_x86.adb_99_7_assert.smt2
[unknown ->  timeout ] spark_2014_all/UFBVDTLIRA/P512-044__exist_on_bv___x86.ads_16_14_postcondition.smt2
[ solved -> 2x slower] spark_2014_all/UFBVDTNIRA/M529-013__modular___modular.adb_7_23_postcondition.smt2
[ solved ->  timeout ] spark_2014_all/UFBVDTNIRA/P508-001__bits_manipulation___bits_manipulation-functions.ads_39_56_bits_manipulation_unsigned.ads_20_7_bits_manipulation_unsigned.ads_43_4_division_check.smt2

**Comment by ajreynol** [comment]
Hi Florian, we have been working on some new techniques for quantified bit-vectors.  Could you perhaps try the option --cbqi-bv?  (this option should not be combined with --no-cbqi)

Several of the above benchmarks go timeout -> solved quickly.  I'll investigate further

**Comment by ajreynol** [comment]
Hi Florian,
From what I can tell, the default configuration is overall +46-2 vs. no-cbqi overall all quantified non-FP benchmarks in spark_2014_all from https://github.com/florianschanda/smtlib_schanda with a 30 second timeout.

Here is the job I ran: https://www.starexec.org/starexec/secure/details/job.jsp?id=25172

I compared the options:
 (default):  --full-saturate-quant
against
(no-cbqi):  --full-saturate-quant --no-cbqi

Are these the right options you are expecting?  Notice that the # of timeouts on the jobs varies significantly: 2517 for default, and 2328 for no-cbqi.

I am independently checking whether --cbqi-bv helps.

My impression is that you care about unknown vs. timeout, is this right?  In other words, a quick response of "unknown" is prefered to a timeout?  If this is the case, I can modify the default configuration so that you get more unknowns.  The issue is that --cbqi when applied to bit-vectors often is too aggressive, but I can modify the default behavior so that you'd see more "unknown" and less timeout.  Let me know if this is something you'd like me to do.

**Comment by florianschanda** [comment]
On Wednesday 29 Nov 2017 15:42:54 Andrew Reynolds wrote:
> My impression is that you care about unknown vs. timeout, is this right?  In
> other words, a quick response of "unknown" is prefered to a timeout?  If
> this is the case, I can modify the default configuration so that you get
> more unknowns.  The issue is that --cbqi when applied to bit-vectors often
> is too aggressive, but I can modify the default behavior so that you'd see
> more "unknown" and less timeout.  Let me know if this is something you'd
> like me to do.

Yes, we prefer a quick unknown to something that is unlikely to ever return; 
but of course I fully understand that this is not easy/generally possible to 
do.

The precise options we're using are: --no-cbqi --no-cond-rewrite-quant

I'll give --full-saturate-quant a go as well, and --cbqi-bv might help in 
places but I need to complete my investigation.

	Florian

**Comment by ajreynol** [comment]
Actually, --full-saturate-quant is probably an option you do not want :)  

The effect of this option generally is that your unknowns will go to -> 80% timeout, 10% unsat, 10% unknown. In other words, this is exactly the kind of option based on what you said in your first sentence you'd prefer to avoid.

I'll add an option today that should make it so that default and no-cbqi should be roughly comparable in terms of unknowns/timeouts.

**Comment by florianschanda** [comment]
I guess since we're using --cbqi-bv by default now I'll close this ticket. I'll report once in a while if there are significant benchmarks that need --no-cbqi.
