### ISSUE TITLE
[SyGuS] Segmantation fault for --strings-exp and --cegqi-si=all

### ISSUE THREAD

**Issue by iwob** [CVC4/CVC4#1404]
Hello, this [problem](https://github.com/CVC4/CVC4/files/1500174/dr-name.txt) executed with the options specified in the title produces a segmentation fault and the following messages:
```
CVC4 suffered a segfault.
Offending address is 0x10
Looks like a NULL pointer was dereferenced.
```

I tried to use --cegqi-si=all because depending on how many preconditions I comment out, I either get immediate unknown, or the solver tries to do something but with no results as of now (the process has still not terminated). I hoped that --cegqi-si would help.

**Comment by ajreynol** [comment]
This is fixed in pull request #1409, the crash no longer occurs, instead CVC4 times out on the input.  

Notice that --cegqi-si=all is not likely to do well on this input. This is because the option has not been adapted for strings.  This is an open (and quite difficult) research question how to lift this technique to strings. For more details, you can see Section 2.1 of http://homepage.divms.uiowa.edu/~ajreynol/arcade17.pdf.
I'll keep you posted if we make progress in this direction.  For now, I would not recommend using --cegqi-si=all on problems with strings.
