### ISSUE TITLE
Performance issue of the quantification over bounded sets

### ISSUE THREAD

**Issue by cristian-mattarei** [CVC4/CVC4#1442]
It seems that the solver is not able to identify quantifications over finite sets.
For instance, given the following formula:

1) E : set of Type_e
2) assert E = {e1,e2, e3}
3a) assert forall (e: Type_e) : ((e in E) => phi(e))

I would expect the solver to identify the quantification 3a) as bounded over the set E, thus instantiating it as:

3b) assert phi(e1) & phi(e2) & phi(e3)

However, it seems that this is not the case, exposing a huge difference in performance between encoding 3a) and 3b). The performance difference can be of different orders of magnitude, as shown by the example in attachment.

[example_3b.zip](https://github.com/CVC4/CVC4/files/1560570/example_3b.zip)
[example_3a.zip](https://github.com/CVC4/CVC4/files/1560571/example_3a.zip)

**Comment by barrettcw** [comment]
Andy - is there an encoding you can suggest that would work better (other
than explicitly doing the instantiation)?

-Clark

**Comment by ajreynol** [comment]
My impression is that explicitly doing instantiation up front is typically best for these kinds of problems, since you get the most propagation when the quantifiers are eagerly expanded.

Bounded quantification in CVC4 is typically useful if you don't know the bound up front (if it is symbolic), or if the bound is too big in practice to expand and you expect that some instantiations are irrelevant.

I had looked at similar examples from Cristian a while ago, and that was my hypothesis.  I could try to improve the heuristics, but actually I found that internally the best heuristic was to expand eagerly, so it may just make sense to do this up front.

**Comment by ajreynol** [comment]
Regarding the actual encoding, I'd have to look deeper into the problem, I'll keep you posted.

**Comment by cristian-mattarei** [comment]
In this particular case, the quantifiers follow a very common pattern (e in E) => phi(e), and in the examples 3a and 3b E is composed of few elements (i.e., 4).

**Comment by ajreynol** [comment]
I think the performance of quantifiers here is expected (~16 seconds for 726 instantiation rounds and ~9000 instantiations).

Unfortunately, I don't see an easy way to make the quantifier instantiation heuristics know to eagerly instantiate up front without introducing a magic number (e.g. if the domain of this quantified formula is fixed and <10000, just expand eagerly).

Let me know if this is still an issue for you. If not, perhaps we can close this issue?
