### ISSUE TITLE
Assertion failure in QuantifiersEngine::check

### ISSUE THREAD

**Issue by 4tXJ7f** [CVC4/CVC4#2040]
Flags: `--finite-model-find --fmf-inst-engine`
File: `AUFBVDTLIA/20172804-Barrett/rec-fun-ijcar2016/wo-wdf/wo_fd_vcs_wdf/2.5-cvc4-HeapSort.scala-29.smt2`

Error:
```
(error "Assertion failure.
void CVC4::theory::QuantifiersEngine::check(CVC4::theory::Theory::Effort)
../../../../src/theory/quantifiers_engine.cpp:461:

  !d_conflict_c.get()
")
```

**Comment by ajreynol** [comment]
This is a strange case. Here's what is happening:
(1) full effort passes with no lemmas (quantifier-free solvers are "SAT"),
(2) during term indexing, quantifiers finds that there are two disequal and congruent terms, say:
theory1 has f(a) != f(b)
theory2 has a = b
This is a conflict, but since quantifiers may run before theory combination, the quantifier-free solvers + combination has not realized it.
(3) quantifiers reports a lemma corresponding to the conflict ~( a = b ^ f(a)!=f(b) ), which is not a SAT conflict since the explanations are not regressed,
(4) quantifiers gets another check at full effort, meaning the quantifier-free theory solvers *still* don't realize there is a conflict.

The fix for now is to have quantifiers engine return when it has realized there is a conflict, having faith that theory combination will do the right thing (split on equalities so that the quantifier-free conflict is discovered).
