### ISSUE TITLE
Unsound when combining fmf-fun and quant-ind options?

### ISSUE THREAD

**Issue by rolfmorel** [CVC4/CVC4#2133]
I am trying to improve the performance of CVC4 for my problem instances (example below) using the '--fmf-fun' and '--quant-ind' commandline options. I am using linear arithmetic, algebraic lists and recursive functions definitions, and believe that my function definitions should be "admissible", as stipulated by the documentation of the '--fmf-fun' option, due to the recursion being well-founded (see [1] for that this should imply admissibility). 

The representative example:

```
(set-logic DTLIA)
(declare-datatypes ((List 1)) ((par (T) ((insert (head T) (tail (List T))) (nil)))))
(define-sort ListInt () (List Int))

(define-fun-rec appendInt ((x (List Int)) (y (List Int))) (List Int)
 (ite (= x (as nil ListInt))
      y
      (insert (head x) (appendInt (tail x) y))
 )
)
(define-fun-rec revInt ((x (List Int))) (List Int)
 (ite (= x (as nil ListInt))
      x
      (appendInt (revInt (tail x)) (insert (head x) (as nil ListInt)))
 )
) 
(declare-const v1 ListInt)
(declare-const v2 ListInt)
(declare-const v3 ListInt)
(declare-const v4 ListInt)
(declare-const v5 ListInt)
(assert (= v1 (insert 2 (insert 3 (insert 1 (as nil ListInt))))))
(assert (and (and (= (revInt v1) v4) (= (revInt v4) v3)) (and (= (revInt v3) v5) (= (revInt v5) v2))))
(check-sat)
(assert (= v2 (insert 4 (insert 5 (insert 3 (as nil ListInt))))))
(check-sat)
```

When running this through cvc4 the expected output is 'sat' and 'unsat'.

When only the '--incremental' option for cvc4 is used the output is 'unknown' and 'unsat', with the response being almost immediate.

When run with the additional option of '--fmf-fun' the output becomes 'sat' and 'unsat', as expected.

Now when the first `(check-sat)` is removed `cvc4 --fmf-fun` hangs and will not return a verdict.

In comes the '--quant-ind' option. With the modified code with only one satisfiability check, `cvc4 --quant-ind` works correctly and produces 'unsat'. Though when the value of `v2` is not asserted it produces 'unknown'. That is for the above code `cvc4 --quant-ind` returns 'unknown  unsat'.

Combining the options seems to lead to unsoundness:
`cvc4 --quant-ind --fmf-fun --incremental` outputs  'sat  sat' for the above code. Clearly the second 'sat' is incorrect. This would seem to be a bug, unless this is to be expected somehow (e.g. due to interaction of the two techniques).

My problem instances are of the kind with only one check-sat instruction, hence I would benefit from both the finite model finding of the '--fmf-fun' option and also of the improved unsatifiability proving from the '--quant-ind' option.

[1] Andrew Reynolds, Jasmin Christian Blanchette, Simon Cruanes, and Cesare Tinelli. 2016. Model Finding for Recursive Functions in SMT. In Proceedings of the 8th International Joint Conference on Automated Reasoning - Volume 9706, Nicola Olivetti and Ashish Tiwari (Eds.), Vol. 9706. Springer-Verlag, Berlin, Heidelberg, 133-151. DOI: https://doi.org/10.1007/978-3-319-40229-1_10

**Comment by ajreynol** [comment]
Thanks a lot for reporting this.  This was indeed caused by a combination of --quant-ind and --fmf-fun. The former enabled a rewrite as an optimization that was incompatible with --fmf-fun.  I've corrected the issue in pull request #2134.

**Comment by rolfmorel** [comment]
As this issue was closed from the pull request, I just wanted to highlight my last comment in regard of enabling both options giving worse performance, and not having having both options enabled leading to incompleteness (i.e. not having '--fmf-fun' enabled means 'unknown' results in case the input is satisfiable).

**Comment by rolfmorel** [comment]
I just saw that you authored the paper on the decision procedure for the DT logic [1]. Could you comment on results regarding the decidability of the DTLIA logic (a combination of two decidable logics), as I haven't been able to find information on it. In deference of your expertise, which solver do you think is likely to work best on this logic, e.g. CVC4 with which mix of options, and what would be the decidablity status of the implementation?

[1]: http://homepage.divms.uiowa.edu/~ajreynol/cade15.pdf

**Comment by ajreynol** [comment]
Regarding your second question about DTLIA, if the logic is quantifier-free (QF_DTLIA), this logic is decidable. The combination of two decidable theories (DT) and (LIA) comes as a consequence of "Nelson-Oppen theory combination", the original reference can be found here: https://www.cs.tau.ac.il/~msagiv/courses/ATP/p245-nelson.pdf although there are a number of somewhat recent papers on theory combination the SMT literature.

With quantified formulas (which implicitly includes problems with recursive functions), things are trickier. The logic UFDTLIA (datatypes, linear arithmetic, and uninterpreted functions, which encode recursive functions), is undecidable since first-order logic is undecidable. 

For problems with quantified formulas, the default setting of cvc4 is close to optimal if you are interested in showing "unsat". The option --quant-ind can be useful in cases where inductive reasoning is required, although most users do not use this option.
The option --finite-model-find (an option that is implied by --fmf-fun) is useful for "sat", for details, see http://homepage.divms.uiowa.edu/~ajreynol/cade24.pdf. The option --fmf-fun is useful for "sat", and when recursive functions are present. 

Most of the other options are lower-level. CVC4 does automatically set certain defaults based on the logic internally, so I would not worry too much about other options.

**Comment by ajreynol** [comment]
Regarding your first question about performance, it turns out that --quant-ind enables a rewrite as a heuristic, which apparently leads to this example being harder to solve "sat". To disable this optimization, use:

--ite-lift-quant=none

With the options "-i --fmf-fun --quant-ind --ite-lift-quant=none", cvc4 quickly gets ( sat, unsat ).

**Comment by rolfmorel** [comment]
Thank you very much for your replies, Andrew.

I will consider not relying on 'sat' results, and thereby benefiting from the efficiency of the default settings of CVC4 (with the addition of "--quant-ind"), as this might suffice for my use case.
