### ISSUE TITLE
Impossible to use an Array within a custom datatype

### ISSUE THREAD

**Issue by rixed** [CVC4/CVC4#2161]
Using cvc4 branch master (as of 2018-07-10) on this SMT2 file:

```smt
(set-info :smt-lib-version 2.6)
(set-logic ALL)
(declare-datatypes
  ( (Type 0) )
  ( ((bool) (number)
     (tuple (tuple-type (Array Int Type)))) ))
```

Produces this error:

```shell
(error "Parse Error: Symbol 'Type' not declared as a type
   (tuple (tuple-type (Array Int Type)))) ))
                                 ^
")
```

The same datatype declaration is accepted by Z3.

**Comment by ajreynol** [comment]
Unfortunately, the datatype you provided is not compliant with the smt standard. The class of datatype definition in fact is not generally supported by the standard algorithm for quantifier-free datatypes in SMT solvers (including Z3)

The relevant requirement that the above definition violates is at the top of page 61 of http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf:

[1] "Note that the sort terms T1, ..., Tm can contain any previously defined sort symbol as well as any of the datatypes D1, ... , Dn, ..."

The problem is that (Array Int Type) is neither a previously defined sort symbol (since it involves Type), nor is it Type itself.  Hence, this kind of datatype should be rejected.  The reason for this restriction is important is that otherwise one could write definitions that are inconsistent.  Here is a simple example to illustrate:

(define-datatype ((Paradox 0)) 
 (( (c (s (Set Paradox))) )) )

It is impossible to assign a cardinality to Paradox.  The restriction I mention above is sufficient for ruling out the above definition, as well as all other problematic datatype definitions.

Z3 should also reject this definition, I actually get this error with version 4.5:
(error "line 4 column 4: invalid sort parameter, symbol or ')' expected")

**Comment by rixed** [comment]
Thank you for the clarification.
Z3 4.7 did accept this, but it was actually a bug (that has been fixed few days ago - see https://github.com/Z3Prover/z3/commit/4915fb080b8978118499bbb6c47a16ef104a0272)
