### ISSUE TITLE
configure fails: error: either /usr/local is not an cryptominisat install tree or it's not yet built

### ISSUE THREAD

**Issue by yurivict** [CVC4/CVC4#2192]
```
checking whether cryptominisat5 was already installed via contrib/get-cryptominisat... no
configure: error: in `/usr/ports/math/cvc4/work/cvc4-1.6/builds/amd64-portbld-freebsd11.1/production':
configure: error: either /usr/local is not an cryptominisat install tree or it's not yet built
See `config.log' for more details
===>  Script "configure" failed unexpectedly.
Please report the problem to greg@unrelenting.technology [maintainer] and
```

When I change to ```autoreconf``` it works.

**Comment by myfreeweb** [comment]
You should've asked me on the bugzilla about this — autoreconf is needed because I patched an m4 script used by configure generation, not the generated `configure` :)

The real issue for CVC4 maintainers should be: "replace all `$CRYPTOMINISAT_HOME/install` with `$CRYPTOMINISAT_HOME` [like this](https://github.com/freebsd/freebsd-ports/blob/053e8b02e455f367143575a1914a61ede28802e2/math/cvc4/files/patch-config_cryptominisat.m4) to allow using system cryptominisat5 by setting cryptominisat home to the system prefix e.g. `/usr/local`"

**Comment by 4tXJ7f** [comment]
I am reopening this and will fix the issue described by @myfreeweb.
