### ISSUE TITLE
--produce-models increases run time significantly

### ISSUE THREAD

**Issue by SeanHeelan** [CVC4/CVC4#2386]
Hi,

When I run cvc4 (latest from git master) on [this ](https://gist.github.com/SeanHeelan/407281401a63226d2a3471f1aa4fc52c) file it finds a satisfying assignment in about a second. However, if I add the `-m` parameter then a solution is no longer found after a few minutes (I haven't let it run any longer). 

Is this a bug or a misuse by me? In the latter case, is there a correct way to get a model out, that I am missing? 

Thanks,
Sean

**Comment by ajreynol** [comment]
Thanks for the report, I can reproduce this behavior.

I took a quick look at the benchmark. It seems this issue is caused by the fact that certain optimizations are incompatible with models currently. In particular, I found that "unconstrained simplification" is disabled when using --produce-models, and the benchmark also takes a long time with --no-unconsrained-simp alone.

We will take a look at whether this optimization (and others necessary to solve this problem quickly) can be made compatible with --produce-models.

**Comment by SeanHeelan** [comment]
I see. Thanks for the update. As it turns out a solution does appear after about 5 minutes, but of course the 1s runtime would be preferable =)

**Comment by aniemetz** [comment]
Unconstrained simplification is indeed incompatible with model generation, and thus switched off when we produce models. Since this is a destructive simplification, reconstructing assignments for the expressions that are simplified away is more involved and we have no plans to extend model generation to support this in the near future. We plan to support this eventually, though.
