### ISSUE TITLE
CVC4 Documentation Unavailable?

### ISSUE THREAD

**Issue by Figler** [CVC4/CVC4#2416]
I'm trying to get some resources on how to properly used the newly release FP theories but can't access pages such at this [this](https://cvc4.cs.stanford.edu/downloads/builds/documentation/internals/cvc4-2018-07-25/classCVC4_1_1FloatingPoint.html) and [this](http://cvc4.cs.stanford.edu/wiki/Rewrite-divk)

Any solution to viewing these pages would be extremely helpful.

Thank you

**Comment by 4tXJ7f** [comment]
Unfortunately, we do not have documentation on how to use the FP theory from our API just yet. It looks like the first link that you were trying to access is outdated (the internal documentation is built as part of our nightly builds and we do not keep old builds indefinitely available due to storage constraints). The most recent version is available [here](https://cvc4.cs.stanford.edu/downloads/builds/documentation/internals/cvc4-2018-08-31/classCVC4_1_1FloatingPoint.html). Note that this class only represents FP constants. The [second link](http://cvc4.cs.stanford.edu/wiki/Rewrite-divk) is not related to FP---it just describes the command line argument `--rewrite-divk`. I am not sure to what extent it is still supported and if the description is still accurate. I'll do some digging. If you have a concrete example for how you want to use the API, I am happy to translate it to API calls.

**Comment by Figler** [comment]
I am going to post another issue specifically with floating point. Thank you for the response.
