### ISSUE TITLE
JVM crash in finalizer

### ISSUE THREAD

**Issue by peterzeller** [CVC4/CVC4#2846]
The finalizers of Expr and Type make the program crash by calling `SmtEngine.dlRef(em)`.

Version
---------

Version: built from repository with tag `1.6`

Example
-----------

(Updated: Changed `mkBoundVar` to `mkVar`)

```
package test;

import edu.nyu.acsys.CVC4.*;

class Cvc4Test {

    public static void main(String... args) throws InterruptedException {
        System.loadLibrary("cvc4jni");
        var em = new ExprManager();
        var smt = new SmtEngine(em);
        smt.setOption("produce-models", new SExpr(true));
        var x = em.mkVar("x", em.integerType());
        var y = em.mkVar("y", em.integerType());
        var z = em.mkVar("z", em.integerType());
        gc("a");
        var a1 = em.mkExpr(Kind.GT, x, em.mkExpr(Kind.PLUS, y, z));
        gc("b");
        smt.assertFormula(a1);
        gc("c");
        var a2 = em.mkExpr(Kind.LT, y ,z);
        gc("d");
        smt.assertFormula(a2);
        gc("e");
        System.out.println(a1);
        System.out.println(a2);
        gc("f");
        var res = smt.checkSat();
        gc("g");
        System.out.println("Res = " + res);
        System.out.println("x =  " + smt.getValue(x));
        System.out.println("y =  " + smt.getValue(y));
        System.out.println("z =  " + smt.getValue(z));
    }

    private static void gc(String msg) throws InterruptedException {
        System.out.println("calling gc " + msg);
        Thread.sleep(100);
        System.gc();
    }

}
```

This example calls `System.gc` to trigger garbage collection and thus calling of the finalizers. Since `System.gc` is just a hint to the runtime, the test won't fail every time.

When it fails the output is something like the following:

```
calling gc a
calling gc b
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x00007fb4a926bfa0, pid=13580, tid=13602
#
# JRE version: OpenJDK Runtime Environment (11.0.1+13) (build 11.0.1+13-Ubuntu-3ubuntu3.18.10.1)
# Java VM: OpenJDK 64-Bit Server VM (11.0.1+13-Ubuntu-3ubuntu3.18.10.1, mixed mode, sharing, tiered, compressed oops, g1 gc, linux-amd64)
# Problematic frame:
# V  [libjvm.so+0xb52fa0]
#
# Core dump will be written. Default location: Core dumps may be processed with "/usr/share/apport/apport %p %s %c %d %P" (or dumping to /home/peter/work/repliss/core.13580)
#
# An error report file with more information is saved as:
# /home/peter/work/repliss/hs_err_pid13580.log
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
```
[hs_err_pid13580.log](https://github.com/CVC4/CVC4/files/2914099/hs_err_pid13580.log)

When I extract `em.integerType()` into a variable so that it does not get collected, I get an error in the finalizer of `Expr` instead:

[hs_err_pid14169.log](https://github.com/CVC4/CVC4/files/2914107/hs_err_pid14169.log)

Workaround
----------------

As a workaround I removed the problematic lines calling `dlRef` from the `delete` method in `Expr.java`, `Type.java` and `SmtEngine.java`. However, this results in memory leaks so it is not a real fix for the problem.

**Comment by 4tXJ7f** [comment]
Thank you for the detailed report. I will take a look.

**Comment by 4tXJ7f** [comment]
It's quite interesting... I can't seem to reproduce the issue with JDK versions older than 11 but it definitely seems to be an issue with JDK 11. I'll keep looking into it but if you need a quick workaround, you may try downgrading your JDK version.

I also have two minor comments on your example:
- To create variables, use `em.mkVar()` rather than `em.mkBoundVar()` (bound variables should only be used with quantifiers). We currently don't seem to be throwing an error if we have bound variables outside of quantifiers but we should fix this.
- You can only use `smt.getValue()` if model generation has been enabled. To do so, use `smt.setOption("produce-models", new SExpr(true));` right after creating the SmtEngine.

**Comment by peterzeller** [comment]
Just to clarify I changed my example above to use `mkVar`, which produces the same crash with Java 11.

**Comment by kfriedberger** [comment]
I would also be interested in a solution for this. We are currently working with CVC4 on Java 8/9, but more and more people are switching to Java 11, where the finalize-Method of several CVC4-related objects causes a SegFault.

**Comment by kfriedberger** [comment]
Any news on this topic?

**Comment by kfriedberger** [comment]
Any news on this topic?

**Comment by kfriedberger** [comment]
Any news on this topic?
The latest version `60ed666d6` still has this problem.

**Comment by andrewvaughanj** [comment]
@kfriedberger is your example different from @peterzeller's? In Peter's example, I can't work out what CVC4 objects are being `gc`'d (by Java), but I can quickly reproduce a similar crash when it is clear what CVC4 objects are being collected: https://github.com/CVC4/CVC4/issues/4421 -- do you have a "simple" reproducer?

@4tXJ7f tells me he is actively working on #4421.

**Comment by kfriedberger** [comment]
I assume that the example from @peterzeller is exactly matching our use case.

The problem definitly appears when the Java GC is running (asynchronously).
The problem appears nondeterministically when running larger examples, with up to hundred queries. Thus, it is quite difficult to track it back to an exact moment.
However, the stacktrace for each crash contains a call to `SmtEngine.dlRef` or `CVC4JNI.delete_*`, independent of the context of the main thread.

**Comment by tgiannak** [comment]
I also ran into this problem. This will reproduce the crash:
```java
import edu.stanford.CVC4.SmtEngine;

public class Test
{
    public static void main(String[] args) throws java.lang.Exception
    {
        System.loadLibrary("cvc4jni");

        Object o = SmtEngine.mkRef(new Object());
        SmtEngine.dlRef(o);
    }
}
```
I did some digging to try to diagnose, working from version 08289dd. I don't think that the GlobalRefs are necessary.

There are a few relevant bits of information that might help with a fix:

- I can't see any reason why `Options` has to be deleted before an `ExprManager` that uses it, just that `ExprManager` can't be used after its `Options` have been deleted. Thus, the `Options` don't have to persist until after the `ExprManager` is deleted, just until after the `ExprManager` is garbage collected. This can be achieved without the use of GlobalRefs, just by having the `ExprManager` class have a normal reference to the `Options` that it is using.
- The same thing looks true about `SmtEngine` and the `ExprManager` that it uses, though that is a more complicated destructor than the one `ExprManager` itself has, so I might have missed something. If I am correct, then again, a simple reference does the trick.
- `Expr` and `Type` aren't actually preserving the `ExprManager` using global refs. The Java `ExprManager` object that they had a reference to was not the owner (`swigCMemOwn == false`) of the underlying C++ `ExprManager` object, so preserving that reference, even with a GlobalRef, was not enough to prevent the underlying `ExprManager` from being deleted. (If it were, then again a simple Java reference in the generated class would be enough.)
- Dealing with `Expr` and `Type` is more complicated, because it looks like it needs an architectural change to the C++ code for how to handle ownership of `ExprManager`. One possibility would be to always use `ExperManager` objects via a `shared_ptr`. Then the Java finalizers will no longer be responsible for deleting the C++ `ExprManager` objects, just for deleting its own `shared_ptr` to decrement the reference count. There might be other options that require smaller changes, but I stopped investigating at that point.

I've got a workaround patch that fixes the crash at the cost of leaking `ExprManager` objects (it addresses the first three points, but not the last). However, I have some red tape to get through before I can release it. I will try to get through that red tape soon.

**Comment by orsonbraines** [comment]
I have checked out and built the most recent commit of master (3bc4a541b6c3a35fae987cc068e0e01937d5c4b1) and I am still getting a (different) SIGSEGV during the JVM finalize. This time the crash is caused CVC4::expr::NodeValue::dec()+0x8b or CVC4::SmtEngine::shutdown()+0xbd.
[hs_err_pid22595.log](https://github.com/CVC4/CVC4/files/4810842/hs_err_pid22595.log)

[hs_err_pid12567.log](https://github.com/CVC4/CVC4/files/4810841/hs_err_pid12567.log)
