### ISSUE TITLE
Universe set not interpreted correctly

### ISSUE THREAD

**Issue by peterzeller** [CVC4/CVC4#2848]
On CVC4 version 1.6:

```
OPTION "finite-model-find" TRUE;
OPTION "produce-models" TRUE;
OPTION "sets-ext" TRUE;
OPTION "incremental" TRUE;
mySort: TYPE;
all: SET OF mySort;
ASSERT (all = UNIVERSE :: SET OF mySort);
%ASSERT FORALL(x: mySort) : x IS_IN all;

ASSERT EXISTS(x: mySort, y: mySort, z: mySort) : DISTINCT(x,y,z);

CHECKSAT;
COUNTERMODEL;
```

This unexpectedly outputs 

`all : SET OF mySort = {} :: SET OF mySort;`. 

When I add the commented line it correctly prints 

`all : SET OF mySort = ({uc_mySort_0} | {uc_mySort_1}) | {uc_mySort_2};`.

By the way: is there a better way than using sets like this to get all elements of a sort from the API?

**Comment by 4tXJ7f** [comment]
@ajreynol, correct me if I am wrong but I think that the universe set is just a superset of all the other sets appearing in the constraints. Since there are none in your case, the universe set is empty. If you have instead:

```
OPTION "finite-model-find" TRUE;
OPTION "produce-models" TRUE;
OPTION "sets-ext" TRUE;
OPTION "incremental" TRUE;
mySort: TYPE;
all: SET OF mySort;
s2: SET OF mySort;
ASSERT (all = UNIVERSE :: SET OF mySort);
ASSERT FORALL(x: mySort) : x IS_IN s2;

ASSERT EXISTS(x: mySort, y: mySort, z: mySort) : DISTINCT(x,y,z);

CHECKSAT;
COUNTERMODEL;
```

Then the output is:
```
all : SET OF mySort = ({uc_mySort_0} | {uc_mySort_1}) | {uc_mySort_2};
s2 : SET OF mySort = ({uc_mySort_0} | {uc_mySort_1}) | {uc_mySort_2};
```

Similarly for:
```
OPTION "finite-model-find" TRUE;
OPTION "produce-models" TRUE;
OPTION "sets-ext" TRUE;
OPTION "incremental" TRUE;
mySort: TYPE;
all: SET OF mySort;
s2: SET OF mySort;
s3: SET OF mySort;
x: mySort;
y: mySort;
ASSERT (all = UNIVERSE :: SET OF mySort);

ASSERT x IS_IN s2;
ASSERT y IS_IN s3;

ASSERT EXISTS(x: mySort, y: mySort, z: mySort) : DISTINCT(x,y,z);

CHECKSAT;
COUNTERMODEL;
```

We get:
```
all : SET OF mySort = {uc_mySort_0} | {uc_mySort_1};
s2 : SET OF mySort = {uc_mySort_0};
s3 : SET OF mySort = {uc_mySort_1};
```

Hope this helps!

**Comment by ajreynol** [comment]
Yes, @4tXJ7f  is correct.

The semantics of universe set is a bit subtle.  In the original example, the set `all` can be interpreted as the empty set, and since there are no other sets in the input, the universe set can also be interpreted as the empty set. Ensuring that all elements occur in the empty set must explicitly done via an axiom like the one you gave.  The motivation for these semantics for the universe set is to ensure that it can always be interpreted as a finite set in (quantifier-free) inputs.


@peterzeller Regarding getting elements of sorts from the API, there isn't currently a straightforward way to get this unfortunately, but I strongly agree with you that it is needed.  I will discuss this with the CVC4 team this week.

**Comment by peterzeller** [comment]
Thanks for the quick replies. 

Maybe you can add a note to the documentation at http://cvc4.cs.stanford.edu/wiki/Sets 

I am closing this issue then, since it is not a bug.
