### ISSUE TITLE
PBE with datatypes/strings fails unexpectedly

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#2935]
I've attached 2 SyGuS problems, test1.sl and test2.sl.  They are exactly the same, except line 9 (which adds a datatype selector to the grammar) is commented out in test2.sl.

test1.sl returns unknown, while test2.sl returns a solution.  Given how small the change to the grammar is, it surprises me that difference regarding CVC4 being able to find a solution.

(Also, slight permutations to the examples seem to let CVC4 succeed. For instance, changing the string "Moon", in the third example in test1.sl, to the string "Mon" let's CVC4 find a solution.)

I would guess this is possibly related to these closed issues:
https://github.com/CVC4/CVC4/issues/2881
https://github.com/CVC4/CVC4/issues/2881

[test.zip](https://github.com/CVC4/CVC4/files/3045340/test.zip)

**Comment by ajreynol** [comment]
Thanks again for sending these.

You are finding a lot of interesting corner cases when combining the PBE algorithm with datatypes. This one is fixed in my latest PR.

You're right, the issues you've reported have triggered similar (yet distinct) corner cases of PBE+datatypes. Thanks for the patience.

**Comment by BillHallahan** [comment]
I've actually been incredibly impressed at how quickly you fix these.  Thank you!
