### ISSUE TITLE
Questions on dump=raw-benchmarks

### ISSUE THREAD

**Issue by florianschanda** [CVC4/CVC4#3005]
Hi,

I am trying to translate some benchmarks containing datatypes from the 2.0 era to 2.6. I figured I could use CVC4 for this:

```
$ cvc4_2019_05_14 --lang=smtlib2.0 --output-lang=smtlib2.6.1 --dump=raw-benchmark --preprocess-only
```

However this applies significant re-writes, some of which result in broken files, e.g.
```
(error "Subexpressions must have a common base type:
Equation: (let ((_let_0 (positions container))) (= _let_0 (get1 _let_0 j)))
Type 1: us_rep6
Type 2: Int
")
```

I tried using --parse-only, but that terminates before the benchmark is dumped. Is there a better way of doing this? Is the broken files a bug? (In which case spark_2014/AUFBVFPDTNIRA/O512-022__robot_navigation_snd___algorithm.adb_515_57_discriminant_check.smt2 from smtlib_schanda triggers it)

**Comment by 4tXJ7f** [comment]
Hmm, so `--dump=raw-benchmark` should actually dump the original assertions without rewriting. I was able to reproduce the issue and will take a closer look. I also noticed that we dump the wrong version (we dump the input SMT-LIB version instead of the output version but that is an easy fix).

Btw. I had to modify the logic in `spark_2014/AUFBVFPDTNIRA/O512-022__robot_navigation_snd___algorithm.adb_515_57_discriminant_check.smt2` from `AUFFPBVFPDTNIRA` to `AUFBVFPDTNIRA`, otherwise CVC4 would not accept it. Do we have an outdated version of the benchmarks?

**Comment by 4tXJ7f** [comment]
Note to self: the issue seems to be that `(get1 (positions container) i)` gets turned into `(positions container)` on the left-hand side.

**Comment by florianschanda** [comment]
The logic string may a bit broken, but I am glad you can reproduce it.

Fixing this would help me a lot since it would save me a lot of time for updating the benchmarks. :)

**Comment by 4tXJ7f** [comment]
@florianschanda I finally got around fixing the issue. Sorry about the delay.

**Comment by florianschanda** [comment]
Great, thanks! I will give it a try and see if everything works now :)
