### ISSUE TITLE
SIGSEGV from Java when setting Options

### ISSUE THREAD

**Issue by kfriedberger** [CVC4/CVC4#3056]
We are using CVC4 (latest version, 2d47884) via the JavaBindings build with `Swig 3.0.8` and `OpenJDK 8.0_212-b03`.
Can someone confirm the segmentation fault for the following snippet?

<pre>
    ExprManager em = new ExprManager();
    Options options = em.getOptions();
    options.setOption("produce-models", "true");
</pre>

We get the following error:
<pre>
# A fatal error has been detected by the Java Runtime Environment:
#  SIGSEGV (0xb) at pc=0x00007f395bae0ad2, pid=22871, tid=0x00007f39bbb81700
# JRE version: OpenJDK Runtime Environment (8.0_212-b03) (build 1.8.0_212-8u212-b03-0ubuntu1.16.04.1-b03)
# Java VM: OpenJDK 64-Bit Server VM (25.212-b03 mixed mode linux-amd64 compressed oops)
# Problematic frame:
# C  [libcvc4.so.6+0xd96ad2]  void CVC4::Options::assignBool<CVC4::options::produceModels__option_t>(CVC4::options::produceModels__option_t, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, bool)+0x92
</pre>

If someone confirms the error, we would request a fix. :-)
If the error is not confirmed, we would like to know your version of Swig and OpenJdk.

**Comment by 4tXJ7f** [comment]
I can confirm the issue and I'll look into fixing it.

**Comment by 4tXJ7f** [comment]
Sorry about the delay. So the issue is that `ExprManager::getOptions()` returns a `const Options&` object. The Java wrapper disregards the `const` qualifier (the [SWIG](http://www.swig.org/Doc3.0/SWIGPlus.html#SWIGPlus_const) documentation on the subject),  which causes issues. I am going to make `ExprManager::getOptions()` private (I seem to remember that we had this issue before). To set options, please use `SmtEngine::getOption()` and `SmtEngine::setOption()`. If that does not work for you, please let us know.

**Comment by kfriedberger** [comment]
Your solution works for me.
