### ISSUE TITLE
Large performance loss from small grammar change

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#3061]
I'm using a recent (git master f6a2704f) version of CVC4 to solve SyGuS problems.  I noticed what seemed like a large performance difference between two very similar grammars.  When I run the below with the `--no-sygus-pbe` flag:
```
(set-logic SLIA)

(synth-fun substring7 ((x1_ String)(x2_ Int)(x3_ Int))String
	((Start String (ntString))
		(ntInt Int
			(0 1 ; the two constants
				x2_ x3_
				(- ntInt ntInt)
			)
		)
		(ntString String
			(x1_
				(ite ntBool ntString ntString)
				(str.substr ntString ntInt ntInt)
			)
		)
		(ntBool Bool
			( 
				(> ntInt ntInt)
			)
		)
	)
)
(constraint (= (substring7 "Hello World Hello" 7 4) "o W"))
(constraint (= (substring7 "Hey" 0 2) "He"))
(check-synth)
```
it takes 1m:52s to find a solution.  However, removing the two Int constants (pointed out in a comment) from the grammar allows CVC4 to find a solution in just 4 seconds.  Is it expected that such a minor change to the grammar would have that large an affect on runtime?  Particularly where the change is just adding/removing constants?

**Comment by ajreynol** [comment]
Thanks for the benchmark.

This is expected behavior.  The smallest solution for this problem is of size 5.  With the constants, the grammar above has around 300,000 terms of size < 5 (if my calculations are correct); without the constants, the grammar has only around 3000.  The runtime difference is simply caused by the fact that cvc4 must try many more candidate solutions. This isn't specific to constants. Generally the tighter your grammar, the faster cvc4's enumerative solver will be.

Hope this helps.

**Comment by BillHallahan** [comment]
Hm, interesting.  Makes sense.  I guess I didn't try to do the math- I didn't realize exactly how much faster that was increasing the number of solutions.  Closing then.  Thanks!
