### ISSUE TITLE
CVC4 reports unknown on LRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3083]
The following formula is unsatisfiable according to the SMTLIB spec on Reals http://smtlib.cs.uiowa.edu/theories-Reals.shtml
```
(assert (not (exists ((f Real))
    (= (/ f 0) 0)
)))
(check-sat)
```
CVC4 reports `unknown` for this formula.
Removing `(not` helps, it gives the correct result which is SAT in that case.

OS: Ubuntu 18.04
Revision: 2c289524f23a2ec481224b2ea569397acbb5e39e

**Comment by ajreynol** [comment]
Thanks for the benchmark.  The logic for this benchmark is also NRA btw, since it involves division by zero.

The benchmark you gave is actually SAT I believe, since division-by-zero can be interpreted as a function that always returns non-zero. (Its negation without `not` is indeed satisfiable as well).

Unfortunately CVC4 is not able to find such a model.

**Comment by ajreynol** [comment]
If you want a CVC4 option that is able to solve this, you can try `--sygus-inference`, which rephrases the SMT problem as a syntax-guided synthesis problem and invokes the subsolver in CVC4 described in this paper http://homepage.divms.uiowa.edu/~ajreynol/cav15a.pdf

**Comment by muchang** [comment]
Thank you for your explanation and suggestions! 
This case should be actually sat, sorry for the imprecise report.
