### ISSUE TITLE
segfault with datatypes and set

### ISSUE THREAD

**Issue by namin** [CVC4/CVC4#3253]
This program, ran with in `cvc4 -m --lang smtlib`
```
(set-logic ALL_SUPPORTED)
(declare-datatypes ((ty 0)) ((
  (arr (arr_param ty) (arr_ret ty))
  (rcd (rcd_set (Set ty))))))
(declare-const x ty)
(declare-const y ty)
(assert (not (= x y)))
(check-sat)
```
crashes with a segfault.
Also, note that it would be well founded to remove the `arr` variant, but then we get a parse error "Symbol `ty` is not declared as type".

I tried with CVC4 version 1.6 and CVC4 HEAD (version 1.8-prerelease [git master 599e788f]).

Thanks.

**Comment by ajreynol** [comment]
Thanks for the benchmark.

The challenging aspect of this benchmark is that your datatype `ty` has a field with `(Set ty)` that contains `ty` but is not `ty` itself.

While these datatypes are technically allowed by the SMT-LIB standard, CVC4 was not designed to handle them.  Here is another example which shows why they are tricky:

```
(set-logic ALL)
(declare-datatype T ((Emp) (Container (s (Set T)) )))
(declare-fun a () T)
(assert (not ((_ is Emp) a)))
(assert (= (s a) (singleton a)))
(check-sat)
```

This is essentially saying that a is a set that contains itself.  Surprisingly, the semantics of combined theories in SMT does not make it clear whether this input is sat or unsat.

Coincidentally, I have recently been in discussion with @barrettcw  and @tinelli  about clarifying whether (1) datatypes like these should be explicitly disallowed in SMT-LIB, or (2) how to resolve semantic issues with them.

If you are interested, I have an experimental branch that parses datatypes like the one you gave (https://github.com/ajreynol/CVC4/tree/dtNonSimpleRec), although notice that this branch sometimes generates incomplete models due to the issues I mention above.

I will keep you posted if there are updates on this.

**Comment by nafur** [comment]
On current master, cvc4 now explicitly rejects such inputs:
```
$ ./bin/cvc4 cur.smt2 
(error "Cannot handle nested-recursive datatype ty")
```
Should we close this issue?

**Comment by namin** [comment]
Thank you. Closing...
