### ISSUE TITLE
incorrect answer when using existential quantifiers in synthesis constraint

### ISSUE THREAD

**Issue by polgreen** [CVC4/CVC4#3320]
I know quantifiers aren't officially supported in synthesis constraints, but I thought I'd try it anyway. I was expecting either a correct answer or "unknown" or an error message but I think CVC4 returned an incorrect answer.

Here's my example, I am trying to write a specification that says "synthesize a function that returns true for at least one input and false for at least one input":
~~~
(set-logic LIA)
(declare-var x Int)
(declare-var y Int)
(synth-fun myfun ((x Int) (y Int)) Bool)
(constraint (exists ((x Int) (y Int)) (myfun x y)))
(constraint (exists ((x Int) (y Int)) (not (myfun x y))))
(check-synth)
~~~
The answer returned by CVC4 was: 
~~~
(define-fun myfun ((x Int) (y Int)) Bool false)
~~~
I don't think that answer satisfies the spec, because the constraint `(exists ((x Int) (y Int)) (myfun x y))` is never satisfied. 

Is this answer incorrect, or is my spec not specifying what I think I am specifying?

**Comment by ajreynol** [comment]
Thanks for the benchmark, we were returning an incorrect solution here.  This is fixed in my latest PR.  Your example is now solved with this solution:
```
(define-fun myfun ((x Int) (y Int)) Bool (= x 0))
```
Indeed CVC4 is not guaranteed to succeed when quantifiers are present in the bodies of sygus conjectures, although as mentioned do feel free to post issues like this.

**Comment by polgreen** [comment]
Impressively quick fix, thanks!
