### ISSUE TITLE
Different error-behavior based on environmental conditions

### ISSUE THREAD

**Issue by robdockins** [CVC4/CVC4#3401]
CVC4 seems to have different behavior on errors when attached to a terminal than when not.

```
$ echo "(get-info :error-behavior)" | cvc4 -i --lang smt2
(:error-behavior immediate-exit)

$ cvc4 -i --lang smt2
cvc4 1.7-prerelease [git master 1955e4b5] assertions:off

<snip>

CVC4> (get-info :error-behavior)
(:error-behavior continued-execution)
```

I'd like to get the `continued-execution` behavior even when running scripts or when attached via pipes to another process. Is there some way to achieve this?

**Comment by nafur** [comment]
I'm not sure whether this is a satisfying answer, but the default is `immediate-exit` now. Furthermore, however, it does not seem like this has any effect on the solver behavior anyway.
Hence, unfortunately, the answer to your question seems to be no.
What kind of errors do you want to continue from?

**Comment by robdockins** [comment]
Well, the original error that gave rise to this ticket was https://github.com/CVC4/CVC4/issues/3402, I believe.  But, usually what I run into is some flavor of "the solver doesn't understand/isn't configured for this problem."  Most commonly, it's caused by nonlinear arithmetic, but can occur anytime we configure a limited logic but then end up going outside the bounds of that logic.

In my setting, I'm using incremental solving to keep track of control-flow paths and to do path satisfiability checks.  If the solver returns an error during this process, I'd prefer to treat that as an "unknown" response and keep going under the assumption that both paths might be satisfiable. With `continued-execution`, I can just `pop` back to a state that still makes sense and retain the rest my context (including any learned clauses and other solver internal goodies).  If the solver exits instead, I have to start a new process and reestablish my context before continuing.  Each time this happens, I pay the process startup costs and the costs of streaming the context to the solver again (which can be nontrivial), in addition to loosing any useful internal state that might have accumulated.

**Comment by nafur** [comment]
I understand from your explanation that you essentially don't know beforehand what logic your problem will be in, set some logic and then go beyond it. This will be a hard error for mainly two reasons:
- When a limited logic is specified, we oftentimes enable certain techniques that may not be sound for a more extensive logic. Thus, there oftentimes is no faster way to extend the logic than restarting the whole solving, and even if there would be a faster way, it can be difficult to figure this out. Making you restart the solver process (instead of doing this restart internally) may be a bit inconvenient for you, but it really is not significantly slower.
- We very much want this do be a hard error. If the user goes beyond the scope of the specified logic, we want to make the user aware of that as aggressively as possible. It oftentimes goes along with a solver behavior that is vastly different from what the user expects.

Given that you seem to use CVC4 as a backend solver for your own tool, I'd suggest that you spend some time thinking about what the proper logic should be, or use `ALL`. If you are not sure what the proper logic would be, we can probably help you with that if you tell us what you throw at CVC4...
