### ISSUE TITLE
CVC4 reports unknown but produces a model on Real formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3427]
Hi, 
For this formula,
```
(set-logic NRA)
(declare-fun a () Real)
(assert (>= a 6.0))
(assert (>= (/ 1.0 (+ a 1.0)) 0))
(check-sat)
(get-model)
```
CVC4 reports unknown but produces a model:
```
% cvc4 --produce-models file.smt2
unknown
(model
(define-fun a () Real 6.0)
)
```
`--sygus-inference` will hang on it:
```
% timeout -s 9 10 cvc4 --sygus-inference --produce-models file.smt2
Killed
```

OS: Ubuntu 18.04
Revision: c547bd5

**Comment by 4tXJ7f** [comment]
AFAIK, when CVC4 returns `unknown`, it may also return a model with the "best" guess so far, so I am not sure if we'd consider this to be a bug. What's interesting, however, is that the model here is actually correct and it looks like there is an issue with quantifiers. If we change the logic to `QF_NRA`, we get `sat` with the same model (somewhat similar to #3407?).

Side note: What's kind of interesting here though is that we could actually rewrite `(>= (/ 1.0 (+ a 1.0)) 0)` to `(>= a 0)` for the case where `a` is not `-1`.

**Comment by ajreynol** [comment]
This is expected behavior. When CVC4 says "unknown", by the SMT-LIB standard, it is required to response to `get-model` queries, according to http://smtlib.cs.uiowa.edu/papers/smt-lib-reference-v2.6-r2017-07-18.pdf page 52 Figure 4.1.  

The option `--sygus-inference` should not be used on this problem.
