### ISSUE TITLE
CVC4 check unsat cores faliure on NRA formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3475]
Hi,
For this formula,
```
(set-logic ALL)
(declare-fun x () Real)
(assert (< x 0))
(assert (not (= (/ (sqrt x) (sqrt x)) x)))
(check-sat)
```
CVC4 reports `unsat`.  
This formula should be `sat` in real arithmathic, since `(/ (sqrt x) (sqrt x))` can be rewrited to `1`.
If I enable `check-unsat-cores`, CVC4 will throw out a fatal failure:
```
Fatal failure within void CVC4::SmtEngine::checkUnsatCore() at 
/home/CVC4/src/smt/smt_engine.cpp:4613
Internal error detectedSmtEngine::checkUnsatCore(): produced core was satisfiable.
```

OS: Ubuntu 18.04
Revision: 17f0468

**Comment by 4tXJ7f** [comment]
@ajreynol It looks like we don't implement constant folding for `sqrt` (so `(not (= (/ (sqrt 1) (sqrt 1)) 1))` is `unsat` as well). Could that be the cause?

**Comment by 4tXJ7f** [comment]
Alright, I have submitted a fix. Note that we can't rewrite `(/ (sqrt x) (sqrt x))` to `1` though because a division by zero has an undefined value. The problem is nevertheless `sat` because if we have for example `x = -1`, we get that `(/ (sqrt x) (sqrt x)) = 1` (`sqrt` of a negative number returns an undefined value but since `sqrt` behaves like a function, we still have that `x = y => f(x) = f(y)`) which is not equal to `-1`.
