### ISSUE TITLE
--sygus-steam prevents finding solution

### ISSUE THREAD

**Issue by BillHallahan** [CVC4/CVC4#3580]
The following SyGuS problem does not seem to be handled well when running with `--sygus-stream`.  Removing `f` (which, trivially, must always just return `true`) results in drastically better performance:
```
(set-logic ALL)
(synth-fun f 
	() Bool 
	((B Bool)) 
	(
		(B Bool (true))
	)
)
(synth-fun g 
	((r Int)) Bool 
	((B Bool) (I Int) (IConst Int)) 
	(
		(B Bool ((= I I) (=> B B)))
		(I Int (r 0 (mod I IConst)))
		(IConst Int ((Constant Int)))
	)
) 
(constraint (g 0))
(constraint (not (g 1)))
(constraint (g 2))
(constraint f)
(check-synth)
```
with only the flag `--lang=sygus2`, CVC4 finds the following solution in <.1s:
```
(define-fun f () Bool true)
(define-fun g ((r Int)) Bool (= 0 (mod r 2)))
```

When the  `--sygus-stream` flag is added CVC4 does not return a solution within 10 minutes.

**Different performance with changes:**
Removing `=>` from the grammar of `g` results in `--sygus-stream` returning `unknown`.  Removing `f`:
```
(set-logic ALL)
(synth-fun g 
	((r Int)) Bool 
	((B Bool) (I Int) (IConst Int)) 
	(
		(B Bool ((= I I) (=> B B)))
		(I Int (r 0 (mod I IConst)))
		(IConst Int ((Constant Int)))
	)
) 
(constraint (g 0))
(constraint (not (g 1)))
(constraint (g 2))
(check-synth)
```
results in `--sygus-stream` finding several solution almost instantly:
```
time cvc4 test.sy --lang=sygus2 --sygus-stream
(define-fun g ((r Int)) Bool (= 0 (mod r 2)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 2)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 3)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 3) 2)))
(define-fun g ((r Int)) Bool (=> (= r (mod r 2)) (= r 0)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 4)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 5)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 6)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 7)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 8)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 9)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 10)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 11)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 12)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 13)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 14)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 2) 15)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 4) 2)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 5) 2)))
(define-fun g ((r Int)) Bool (= 0 (mod (mod r 6) 2)))
```

**Comment by ajreynol** [comment]
Hi,

Thanks for the benchmark.  For some detail, when multiple functions are present, CVC4 uses a different strategy for enumeration (the "smart" strategy of Section 2 of https://homepage.divms.uiowa.edu/~ajreynol/cav19b.pdf), whereas for single functions, it commonly uses the strategy in Section 3.  That's why you are seeing a large change in performance when adding `f` (albeit a trivial function).

There is bug that is causing non-termination related to the use of (Constant Int) as the denominator of an application of `mod`.  Notice that strictly speaking, the grammar you provided is non-linear arithmetic, since it permits modulus-by-zero.  You may want to try an alternative formulation that doesn't permit modulus-by-zero (say `1 + abs([any constant])`.  Regardless I should be able to fix this soon.

-Andy

**Comment by BillHallahan** [comment]
Got it!  Thanks for the detailed explanation, and the tip about mod!
