### ISSUE TITLE
CVC4 suffered a segfault: Offending address is 0x30

### ISSUE THREAD

**Issue by pointhi** [CVC4/CVC4#3601]
**Version:** 1.7 compiled with GCC version 9.1.1 20190605 (Red Hat 9.1.1-2)

**Command-line:**

```
$ cvc4 --lang=smtlib2.5 --incremental null_pointer_dereference.smt
sat
CVC4 suffered a segfault.
Offending address is 0x30
Looks like a NULL pointer was dereferenced.
```

**File:** *null_pointer_dereference.smt*
```smt
(set-logic QF_BV)
(declare-fun a () (_ BitVec 32))
(declare-fun b () Bool)

(assert (= b (bvslt a (_ bv1 32))))
(assert (not b))
(check-sat)
; sat
(assert (= (bvadd a a (bvsrem (_ bv10 32) a) (_ bv22 32)) (_ bv1234 32)))
(check-sat)
; CVC4 suffered a segfault.
; Offending address is 0x30
; Looks like a NULL pointer was dereferenced.
```

**Comment by mpreiner** [comment]
@pointhi Does this still occur on current master?

**Comment by pointhi** [comment]
@mpreiner yes, it is reproducible on ```CVC4 version 1.8-prerelease [git master 9e94e0bf]```

**Comment by mpreiner** [comment]
OK, I can reproduce it. 

A debug build produces the following:
```
$ bin/cvc4 ../segfault.smt2  --incremental --lang=smtlib2.5
sat
Fatal failure within void CVC4::theory::bv::TheoryBV::explain(CVC4::TNode, std::vector<CVC4::NodeTemplate<false> >&) at /home/ma/git/cvc4-fork/src/theory/bv/theory_bv.cpp:880
Check failure

 wasPropagatedBySubtheory(literal)

Aborted (core dumped)
```
If option `--lang=smtlib2.5` is omitted the error does not occur.

**Comment by 4tXJ7f** [comment]
It looks like this was happening because theory combination was not enabled for the first check-sat call and then getting enabled for the second one (because a UF was introduced) leading to issues. a48cafdd09c3ff8cb9984bad930343958c30ce56 (which fixed issues on other inputs with this pattern) fixes the issue by eagerly adding UF if BV is in the logic (if division/mod zero is treated as a UF).
