### ISSUE TITLE
--check-unsat-cores Fatal Failure at CVC4/src/smt/smt_engine.cpp:4645

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#3655]
Hi,
For this formula,
```
(declare-sort A 0)
(declare-fun e (A) A)
(declare-fun c (A A) A)
(declare-fun h (A A) A)
(declare-fun b (A) Bool)
(declare-fun d (A) Bool)
(assert (let ((a!1 (forall ((f A) (i A)) (distinct (h f i) (e (c f i))))))
  (not a!1)))
(assert (let ((a!1 (forall ((j A)) (or (not (b j)) (d (e j))))))
  (and a!1 (forall ((i A)) (b i)) (forall ((g A)) (not (b g))))))
(check-sat)
```
`cvc4 --check-unsat-cores` throws out a fatal failure:
```
Fatal failure within void CVC4::SmtEngine::checkUnsatCore() at 
CVC4/src/smt/smt_engine.cpp:4645
Internal error detectedSmtEngine::checkUnsatCore(): could not check core result unknown.
Aborted
```

OS: Ubuntu 18.04
Revision: bde056b

**Comment by ajreynol** [comment]
I can confirm this is caused by our techniques for quantifier instantiation: we can show the original problem unsatisfiable, but not the (minimized) unsat core.  It is expected that we could get unknown for reduced unsat cores with quantifiers. 

I think the solution to this issue is to weaken our guarantees on when unsat cores is guaranteed to work.  @4tXJ7f  what do you think?
