### ISSUE TITLE
strings-print-ascii soundness bug on QF_S formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4179]
Hi,
For this formula:
```
(set-option :strings-print-ascii true)
(declare-fun a () String)
(assert (= (str.code a) 128))
(check-sat)
```
CVC4  gives an incorrect answer:
```
[555] % cvc4-1.7 --quiet small.smt2
sat
[556] % cvc4 --quiet small.smt2
unsat
[557] % 
[557] % cat small.smt2
(set-option :strings-print-ascii true)
(declare-fun a () String)
(assert (= (str.code a) 128))
(check-sat)
```

OS: Ubuntu 18.04
Commit: 01b2570

**Comment by 4tXJ7f** [comment]
Thanks for reporting this. The issue here is that we assert that code values have to be in the range [0, alphabet_size) (see [here](https://github.com/CVC4/CVC4/blob/27ac2ce712b0bcfdef83e2d44dd210f667ab7959/src/theory/strings/theory_strings.cpp#L1105-L1109)). This is not quite correct for this option because the alphabet size is 128 but it starts at code point 32. However, I'd advocate for simply removing the option (especially given the new strings standard). Thoughts @ajreynol?

**Comment by ajreynol** [comment]
Unsat is the intended answer here, since code should be in the range [0, alphabet_size).  `strings-print-ascii` limits cvc4 to alphabet size of 128, although indeed as Andres points out this is highly confusing since then code points do not correspond to code points.  

I do think it may be useful to continue to support this option, since it is a good option for casual users who don't want unprintable characters.  Perhaps we should generalize its handling so that it shifts the range of code points it handles?
