### ISSUE TITLE
QF_BV logic soundness bug triggered by legacy smt-lib set-info

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#4198]
Hi, 
the below trace shows a (trivial) soundness issue in CVC4. 
```
% cvc4-936e9c4 --quiet bug.smt2
sat
% cat bug.smt2
(set-info :smt-lib-version 2.0)
(set-logic QF_BV)
(define-fun a () (_ BitVec 1) (_ bv0 1))
(assert (= (bvudiv a a) (_ bv0 1)))
(check-sat)
```
Removing the smt-lib version set-info comment or replacing the version by 2.6 makes the bug disappear.

OS: Ubuntu 18.04
Commit 936e9c4

**Comment by ajreynol** [comment]
This is the correct answer.  In SMT-LIB 2.0, `bvudiv` is interpreted as a partial function.  Thus, a = 0 is a satisfying solution to this problem.

**Comment by zhendongsu** [comment]
Andrew, in that case, Z3's answer is incorrect then, correct?

**Comment by ajreynol** [comment]
It depends on your interpretation of what it means to set legacy SMT-LIB versions.  We adopt the policy that the SMT-LIB version sets both the syntax and semantics of the SMT-LIB version at the time, whereas Z3 likely just changes the syntax.   

The motivation for this choice was so that the status of SMT-LIB version 2.0 benchmarks did not change when the official semantics changed, thus this benchmark remains "sat".

It should also be noted that we are planning to delete our support for legacy SMT-LIB versions in the near future.

**Comment by zhendongsu** [comment]
Thanks for this further explanation, Andrew; appreciated!
