### ISSUE TITLE
Soundness bug with --quant-anti-skolem

### ISSUE THREAD

**Issue by wintered** [CVC4/CVC4#4403]
```
$z3 bug.smt2                          
sat
$cvc4 -q bug.smt2                     
unknown
$cvc4 -q --quant-anti-skolem bug.smt2 
unsat
$cat bug.smt2
(define-fun-rec f ((b Int)) Int (ite (= b 0) 0 (+ (f b) b)))  
(check-sat)
```

OS: Ubuntu 18.04
Commit: 30c0e86

**Comment by wintered** [comment]
```
[564] % cvc4 -q bug.smt2 
unknown
[565] % cvc4 -q bug.smt2 --fmf-fun-rlv
sat
[566] % cvc4 -q bug.smt2 --fmf-fun-rlv 
sat
[567] % cvc4 -q bug.smt2 
unknown
[568] % cvc4 -q --fmf-fun bug.smt2 
sat
[569] % cvc4 -q --quant-anti-skolem bug.smt2
unsat
[570] % cvc4 -q --quant-anti-skolem --fmf-fun bug.smt2
sat
[571] % cat bug.smt2 
(define-fun-rec a ((b Int)) Int (ite (= b 0) 0 (+ (a b) b)))
(check-sat)
[572] %
```

**Comment by ajreynol** [comment]
This problem is "unsat", the define-fun-rec you give is equivalent to 
`(assert (forall ((b Int)) (= (a b) (ite (= b 0) 0 (+ (a b) b)))`
which can be shown unsat by instantiating with any b != 0.  Z3's answer of "sat" is incorrect.

**Comment by wintered** [comment]
Andrew, thank you for the quick reply. I may indicate, however, that `cvc4 --fmf-fun` gives the incorrect answers `sat` as well.

**Comment by ajreynol** [comment]
Yes, `--fmf-fun` changes the semantics of the input problem to assume recursive functions are "admissible", see Definition 2 of http://homepage.divms.uiowa.edu/~ajreynol/ijcar16a.pdf.  Z3 probably has a similar assumption by default.  

In practice, define-fun-rec is used for function definitions that are not logically inconsistent; SMT solvers tend to assume they are (this is what --fmf-fun enables), which makes this problem go unsat -> sat. However, the problem is officially "unsat" by SMT-LIB semantics.

**Comment by ajreynol** [comment]
You can also read page 10 of the above paper for more details on why this is expected behavior.
