### ISSUE TITLE
Soundness bug on using (set-logic QF_AUFBVLIA) on BV formula 

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#4437]
Hi,
For this case, CVC4  gives an incorrect answer:
```
[570] % cvc4 small.smt2 
sat
[571] % cvc4 --strings-exp small.smt2 
unsat
[572] % cat small.smt2 
(set-logic QF_AUFBVLIA)
(declare-fun a () (_ BitVec 8))
(declare-fun b () (_ BitVec 8))
(assert (forall ((c (_ BitVec 8))) (= (bvashr c a) b)))
(check-sat)
[573] %
```
unsat is the right answer; strictly speaking, the formula is not QF_AUFVLIA because of the forall, but cvc4 doesn't complain and give an incorrect answer.

OS: Ubuntu 18.04
Commit: 8236d7f

**Comment by ajreynol** [comment]
Thanks for the bug report.

The problem is UNSAT.  The reason we are answering SAT is a combination of two things:
- Unconstrained simplification pass is incorrectly replacing the body of the quantifed formula with a fresh variable.  It is being allowed to run since the logic is incorrectly specified as QF_.
- `--strings-exp` is expanding the logic to allow quantifiers, thus silently avoiding what should be a logic exception.

The solution is to make unconstrained simplification more robust to catching when quantifiers are present.

**Comment by zhendongsu** [comment]
Here is another (even simpler) instance that probably could also be included as a regression test: 

```
[516] % cvc4 small.smt2
sat
[517] % cat small.smt2
(set-logic QF_AUFBVLIA)
(declare-fun a () Int)
(assert (forall ((b Int)) (= a b)))
(check-sat)
[518] % 
```
