### ISSUE TITLE
Invalid model for NIA formula (theory_engine.cpp:2283) (check-models, check-unsat-cores)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4457]
Hi,
For the following formula:
~~~~
(set-logic NIA)
(set-option :check-unsat-cores true)
(declare-const i2 Int)
(assert (! (forall ((q0 Int) (q1 Bool) (q2 Bool) (q3 Bool) (q4 Int) (q5 Int) (q6 Int) (q7 Bool)) (=> (<= i2 0) false)) :named IP_3))
(push 1)
(assert false)
(push 1)
(check-sat)
(pop 1)
(check-sat)
(pop 1)
(check-sat)
~~~~

CVC4 throws out a fatal failure:
~~~~
unsat
unsat
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:2283
Internal error detectedTHEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (>= i2 1)
Model value: false

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ad7907a

**Comment by nafur** [comment]
This example works fine on the current master. It works since a6c8c9a293eca7cd753368d7f23f9978deb2b2d5, however it seems to me that this commit merely hides the underlying issue, but does not fix it.
Note that a6c8c9a293eca7cd753368d7f23f9978deb2b2d5 only moves when the theoryof-mode is changed under some conditions, but setting `--theoryof-mode` either way does not reveal the issue on the current master.

**Comment by nafur** [comment]
As per internal discussion: this assertion fails under certain conditions if quantifiers are present that do not necessarily indicate an error condition. This is why a6c8c9a293eca7cd753368d7f23f9978deb2b2d5 has protected this assertion by the new option `--debug-check-models`. We thus close this issue.
