### ISSUE TITLE
Invalid model for QF_LIA and QF_LRA formulas (theory_engine.cpp:2283) (check-models, fmf-fun)

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4462]
Hi,
For the following formula:
~~~~
(set-logic QF_LIA)
(set-option :fmf-fun true)
(assert (< (div 0 0) 0))
(check-sat)
~~~~

CVC4 throws out a fatal failure:
~~~~
Fatal failure within void CVC4::TheoryEngine::checkTheoryAssertionsWithModel(bool) at /home/peisen/test/tofuzz/CVC4/src/theory/theory_engine.cpp:2283
Internal error detectedTHEORY_ARITH has an asserted fact that the model doesn't satisfy.
The fact: (not (>= (intDivByZero 0) 0))
Model value: false

Aborted (core dumped)
~~~~

OS: Ubuntu 16.04
Commit: ad7907adf

**Comment by rainoftime** [comment]
~~~~
(set-logic QF_LRA)
(set-option :fmf-fun true)
(declare-const r3 Real)
(assert (distinct r3 0.0 (/ 0.220806377 0.0)))
(check-sat)
~~~~

**Comment by 4tXJ7f** [comment]
This is not a valid benchmark according to the SMT-LIB standard for QF_LIA/QF_LRA. [QF_LIA](http://smtlib.cs.uiowa.edu/logics-all.shtml#QF_LIA) does not accept `div` at all (even for divisions by constants) whereas [QF_LRA](http://smtlib.cs.uiowa.edu/logics-all.shtml#QF_LRA) only allows division (`/`) to specify rational constants and the denominator cannot be zero in that case. CVC4 is a bit more lenient and allows divisions by non-zero constants since they can be rewritten to linear constraints. The issue here was that we were not properly warning about divisions by zero being unsupported in QF_LIA/QF_LRA. For non-linear logics, we are not extending the logic with UF, which is needed to encode the result of a division by zero. As a result, theory combination was not enabled and we ended up with these model issues. I have confirmed that commit 52082c72d78eee219e3049285d5df559dacac8b5 introduced the appropriate error message:

```
(error "A non-linear fact was asserted to arithmetic in a linear logic.
The fact in question: (div 0 0)
")
```
