### ISSUE TITLE
CVC4 Linux release 1.8 prints 1.9 as its version

### ISSUE THREAD

**Issue by zvonimir** [CVC4/CVC4#4697]
I downloaded release 1.8 using this link: https://github.com/CVC4/CVC4/releases/download/1.8/cvc4-1.8-x86_64-linux-opt

When I run it with `--version`, this is what gets printed:
```
This is CVC4 version 1.9 [git master 733083c3]
compiled with GCC version 5.4.0 20160609
on Jun 19 2020 12:13:36
```
It seems that neither the printed version nor the printed git commit hash match what I would expect to see by looking at the GitHub release.

**Comment by 4tXJ7f** [comment]
Thanks a lot for the report. This is very likely happened because of an issue with our build system where we didn't properly update the Git information associated with a build. By coincidence, I have submitted a PR to fix this issue earlier today (https://github.com/CVC4/CVC4/pull/4696). Once this PR has been merged, I will update the binaries.

**Comment by zvonimir** [comment]
This is just a gentle reminder to update the binaries now that the pull request above got merged. Thanks!

**Comment by zvonimir** [comment]
FYI, this problem persists. It would be great to update the binaries as suggested above at some point. Thanks!

**Comment by 4tXJ7f** [comment]
Sorry about the delay, I need to look into an issue with our build server to get the binaries rebuilt. I will do so ASAP.

**Comment by zvonimir** [comment]
Hi there! It's me again :). Any news on this? Thanks!

**Comment by 4tXJ7f** [comment]
Apologies for the long delay. I have replaced the builds and they should now print out the correct version information. Please let me know if you run into other issues.
