### ISSUE TITLE
(default) Solution soundness bug on QF_ABV formulas

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4771]
~~~~
(set-logic ALL)
(declare-fun arr0 () (Array (_ BitVec 12) (_ BitVec 6)))
(assert (let ((_let_6 (store arr-0 (concat #b010001 (_ bv0 6)) (_ bv0 6)))) (= (store _let_6 (_ bv0 12) #b010001) (store _let_6 (_ bv0 12) (_ bv0 6)))))
(check-sat)
~~~~

cvc4 a1941114a yields `sat`,
but both z3 and yices2 (latest commits) yield `unsat`.

**Comment by rainoftime** [comment]
After adding ``--check-models`, cvc4 can return `unsat`

**Comment by 4tXJ7f** [comment]
Thanks a lot for the report, this is a real bug. Preprocessing the input with CVC4 and then delta-debugging it with [ddSMT](https://github.com/aniemetz/ddSMT) (` ./ddsmt.py -c <path to z3> <input file> <minimized file> <path to cvc4>` does the trick and only take a couple of seconds to complete) results in the following input:

```
(set-logic ALL)
(declare-fun arr-6808665888080864687_6808665888091689937-0 () (Array (_ BitVec 12) (_ BitVec 6)))
(assert (let ((_let_6 (store arr-6808665888080864687_6808665888091689937-0 (concat #b010001 (_ bv0 6)) (_ bv0 6)))) (= (store _let_6 (_ bv0 12) #b010001) (store _let_6 (_ bv0 12) (_ bv0 6)))))
(check-sat)
```

Please submit delta-debugged inputs in the future (see point 4 in the [Fuzzing Guidelines](https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4#general-guidelines)). Please also make sure to check that the bug can be triggered in our latest nightly build (this may have happened here but the commit mentioned in the post above only mentions a very recent commit, so I thought that I'd point this out). The guidelines help us developers to assess and fix the reported bugs more quickly.

**Comment by rainoftime** [comment]
Here is another formula
~~~~
(declare-fun _substvar_42_ () (Array (_ BitVec 9) (_ BitVec 9)))
(declare-fun _substvar_75_ () (Array (_ BitVec 9) (_ BitVec 9)))
(declare-fun _substvar_76_ () (Array (_ BitVec 9) (_ BitVec 9)))
(declare-fun _substvar_82_ () (Array (_ BitVec 9) (_ BitVec 9)))
(declare-fun _substvar_83_ () (Array (_ BitVec 9) (_ BitVec 9)))
(declare-fun _substvar_95_ () (Array (_ BitVec 9) (_ BitVec 9)))
(assert (or (= _substvar_42_ (store _substvar_76_ #b100111101 (_ bv0 9)) (store _substvar_83_ #b100111101 #b100111101)) (= _substvar_75_ (store (store _substvar_82_ (_ bv0 9) (_ bv0 9)) #b100111101 (_ bv0 9)) (store (store _substvar_95_ #b100111101 #b100111101) (_ bv0 9) (_ bv0 9)))))
(check-sat)
~~~~

**Comment by 4tXJ7f** [comment]
I've started to look into this. It looks like the culprit is `--arrays-lazy-rintro1`. Given two stores such as: `(store (store A #b00 #b1)` and `(store (store A #b00 #b0) #b10 #b0)` that are supposed to be equal, we instantiate the RIntro1 inference rule, resulting in the inference that `(= (select (store (store A #b00 #b1) #b10 #b0) #b10) #b0)` and `(= (select (store (store A #b00 #b0) #b10 #b0) #b10) #b0)`. However, while we register `(store A #b00 #b1)` and `(store A #b00 #b0)`, we never bother checking their equivalence and thus we never end up applying RIntro1 to those terms and thus we never detect the conflict. When `--arrays-lazy-rintro1` is disabled, we apply RIntro1 to all store terms being registered, so we don't have that problem. We need to rethink how to do `--arrays-lazy-rintro1` in a safe manner.
