### ISSUE TITLE
Value of option `:produce-proofs` impacts result of `check-sat` (QF_NIA).

### ISSUE THREAD

**Issue by dde-cls** [CVC4/CVC4#4792]
Changing option `:produce-proofs` from false to true results in an `unknown` answer instead of `unsat`.

Example file:
```
(set-logic QF_NIA)
(set-option :print-success false)
(set-option :produce-proofs false)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)

(assert (<= 1 c))
(assert (<= 0 b))
(assert (<= 0 a))

(declare-fun q1 () Int)
(declare-fun r1 () Int)

(assert (<= 0 r1))
(assert (< r1 c))
(assert (= b (+ (* c q1) r1)))

(assert (! (not (= (mod (+ a r1) c) (mod (+ a b) c))) :named goal))
(check-sat)
(exit)
```

**Version**
`CVC4 version 1.7 [git master 84da9c0b]`

**Comment by nafur** [comment]
On the current master (d5141e4086898bb66809c76d4614503e3a2efd6e), both versions yield unknown. I doubt that this makes the situation any better, though...
With `--proof`, however, we get a bunch of leaks on this input:
```
(set-logic QF_NIA)
(declare-fun a () Int)
(declare-fun b () Int)
(declare-fun c () Int)
(declare-fun r1 () Int)
(assert (= b (+ r1 c)))
(assert (= (mod r1 c) (mod b a)))
(check-sat)
```

**Comment by ajreynol** [comment]
This is expected behavior. 

Btw, if you want CVC4 to "try harder" for nonlinear arithmetic problems instead of answering "unknown", use `--nl-ext-tplanes`, using this we get unsat on this problem instead.

Also, it should be noted that the current proof code is undergoing a major refactoring. Thus the option `--produce-proofs` is not robust in its current state.

I'm closing this issue, do let us know if there are any further issues with nonlinear arithmetic in CVC4.
