### ISSUE TITLE
(default) Performance issue on QF_S formula

### ISSUE THREAD

**Issue by rainoftime** [CVC4/CVC4#4830]
Hi, for this instance
~~~~
(set-logic QF_S)
(declare-fun _substvar_129_ () String)
(declare-fun _substvar_158_ () String)
(declare-const Str7 String)
(declare-const Str14 String)
(declare-const Str19 String)
(declare-const v12 Bool)
(declare-const v13 Bool)
(assert (or (str.suffixof (str.++ Str7 "xqxgqj" "" "vikfooqqlg") (str.++ (str.++ "" "" Str14 "yazjgr" "") _substvar_158_ "ysvbhg")) false (str.suffixof (str.++ "vvfmigelhu" Str19 "") Str14) false))
(check-sat)
~~~~

cvc4 4caca6f74c
~~~~
 time z3 xx.smt2
sat

real    0m0.261s
user    0m0.220s
sys     0m0.036s

 timeout 10s cvc4  --strings-exp xx.smt2                                                                                             
CVC4 interrupted by SIGTERM.

~~~~

**Comment by 4tXJ7f** [comment]
I cannot reproduce this issue. With 4caca6f7, this problem is solved in 0.09s on my machine (production build). How did you configure CVC4? Could you double check?

**Comment by rainoftime** [comment]
Compiled with asan, ubsan and in debug mode.

After `make clean; make`, this case is solved in 7 seconds.

**Comment by 4tXJ7f** [comment]
We are not really concerned with performance when running in debug and/or with ASan/UBSan because these configurations (as the names indicate) are for debugging/testing purposes only (users are not expected to use those kinds of builds). Performance issues should only be reported when they affect production builds.
