### ISSUE TITLE
bitvector proofs are huge (180KB for `x=64'b0 /\ y=64'b0 -> x=y)

### ISSUE THREAD

**Issue by andres-erbsen** [CVC4/CVC4#4965]
CVC4 produces huge proofs for trivial bitvector problems. For example, `x=64'b0 /\ y=64'b0 -> x=y` results in 180KB of proof. This gets in the way of using SMTCoq for program verification because this proof takes a minute to ingest ([smtcoq issue #72](https://github.com/smtcoq/smtcoq/issues/72)). For comparision, Z3 produces short proof output for the same files; though I understand that it is using a higher-level proof language that is more difficult to check. 

I am wondering whether this proof size is inherent given the current design of CVC4 (a limitation of the output language?) or perhaps it is just a result of some information being not tracked properly?

Thanks,
Andres

[x.txt](https://github.com/CVC4/CVC4/files/5143474/x.txt) | [z.txt](https://github.com/CVC4/CVC4/files/5143476/z.txt) | [x.pf.txt](https://github.com/CVC4/CVC4/files/5143537/x.pf.txt) | [z.pf.txt](https://github.com/CVC4/CVC4/files/5143538/z.pf.txt)

```
browse@ashryn ~ % cvc4 --lang=smt z.txt | wc
   1234   32130  180794
browse@ashryn ~ % cvc4 --lang=smt x.txt | wc
   1238   31979  179913
```

**CVC4 version/commit**: `This is CVC4 version 1.8 compiled with GCC version 10.1.0`
**Operating system**: Arch Linux, up to date as of two weeks ago.
**`configure.sh` options**: [PKGBUILD](https://github.com/archlinux/svntogit-community/blob/363015967640d56f64cced939b23388242799cea/trunk/PKGBUILD#L42)

**Comment by HanielB** [comment]
There are a few points to be taken into account here. 

In this particular case the CVC4 proof is bigger than what you would expect because CVC4 is solving this problem via bitblasting the BV constraints, as opposed to solving it via rewriting, as Z3 is (from what I can gather from Z3's proof of `x.txt`). This is expected, as in proof-production mode CVC4 disables several preprocessing optimizations. This is so that the proofs produced by CVC4 will not have holes (as the Z3 ones often have), thus increasing proof-checking complexity. In non-proof-producing mode CVC4 also solves this problem without using bitblasting.

Note however that for any non-trivial problem SMT solvers will use bitblasting. Thus, necessarily, if the bitblasting reasoning is to be represented, the proofs will be big (in general much bigger than this one). This is something that must be taken into account by the consumer of bitvector proofs.

All that said, we are open to suggestions on how we might facilitate the integration of bitvector proofs in SMTCoq. We are currently completely reimplementing the proof infrastructure in CVC4 and will be happy to improve the output. One of the goals is to have different backends, so we can print proofs in different formats (such as LFSC or the veriT proof format, for example).
