### ISSUE TITLE
(check-unsat-core) Performance issue on QF_NRA formula with sqrt

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5141]
Hi, for this incremental formula, CVC4 hangs on it with the option check-unsat-core:

```
[537] % time cvc4 --incremental -q small.smt2
sat
sat
real  0m0.017s
user  0m0.007s
sys   0m0.004s
[538] % 
[538] % timeout -s 9 10 cvc4 --incremental --check-unsat-cores -q small.smt2
sat
Killed
[539] % 
[539] % cat small.smt2
(declare-fun a () Real)
(push)
(assert (= a 1.0))
(assert (distinct (sqrt 1.0) 0))
(check-sat)
(pop)
(assert (distinct (sqrt 1.0) (sqrt a)))
(check-sat)
[540] %
```

OS: Ubuntu 18.04
Commit: 160a3f5

**Comment by HanielB** [comment]
This is expected behavior. Currently when unsat cores are on it's as if one uses `--simplification=none`, which the reason this benchmark goes from solvable to hanging. 

As in internal note: with the new proof insfrastructure we do not force `--simplification=none`, so this benchmark goes through without problems.
