### ISSUE TITLE
Model soundness / parser bug related to (reset-assertions)

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5163]
Hi, for this formula with (reset-assertions), CVC4 gives an unsound result. 
```
[596] % z3 small.smt2
unsat
[597] % cvc4 small.smt2
sat
[598] % 
[598] % cat small.smt2
(set-logic ALL)
(define-fun a () Bool false)
(reset-assertions)
(assert a)
(check-sat)
[599] %
```

OS: Ubuntu 18.04
Commit: 69e1472

**Comment by ajreynol** [comment]
On second glance, I believe the proper behavior is to complain that `a` is undefined: `reset-assertions` clears assertions *and symbol declarations* when the option `global-declarations` is false, which it is by default.  Thus the bug here is that reset-assertions should clear the symbol table in the parser, which would lead to the error being thrown.
