### ISSUE TITLE
Invalid model for QF_S formula

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5520]
```
[574] % cvc4 --produce-models small.smt2
sat
(
(define-fun x () String "")
)
unsat
[575] % 
[575] % cat small.smt2
(set-logic QF_S)
(declare-fun x () String)
(assert
 (not
 (str.in_re (str.++ "a" x "ca")
  (re.*
  (re.++ (re.union (str.to_re "a") (str.to_re "b"))
   (re.union (re.* (str.to_re "a")) (str.to_re "b") (str.to_re "c")))))))
(check-sat)
(get-model)
(reset)
(set-logic QF_S)
(define-fun x () String "")
(assert
 (not
 (str.in_re (str.++ "a" x "ca")
  (re.*
  (re.++ (re.union (str.to_re "a") (str.to_re "b"))
   (re.union (re.* (str.to_re "a")) (str.to_re "b") (str.to_re "c")))))))
(check-sat)
[576] %
```
It still triggers after PR5518 for fixing the refutation unsoundness in QF_S.

Commit: 07c7b87

**Comment by 4tXJ7f** [comment]
With 07c7b87, I am getting `"A"` as the model for `x`, which both CVC4 and Z3 seem to be happy with. I had to use `--strings-exp` though because we get a negative membership constraint during solving. Which platform/configuration are you running on? Could you double check that you are running the version with the fix? Thanks!

**Comment by muchang** [comment]
Thank you, @4tXJ7f. I double-checked this issue with 07c7b87 and also got `"A"` for `x`. Maybe the previous build was broken, you could close this issue.
