### ISSUE TITLE
Does CVC4 have the equivalent of Z3's fp.to_ieee_bv?

### ISSUE THREAD

**Issue by sree314** [CVC4/CVC4#5537]
I know the SMT-LIB floating point theory does not support converting floating point numbers to bit vectors. However, Z3 has an (non-standard) `fp.to_ieee_bv` function that can do this, and [this paper](https://ssvlab.github.io/lucasccordeiro/papers/nsv2020.pdf) (page 21) suggests CVC4 does too. I looked in the documentation and in the source, but couldn't figure out if such a function exists.

Does CVC4 have this functionality? 

We're building bit vector functions of some floating point functionality not supported by the theory and being able to switch back and forth between the representations would be invaluable.

**Comment by martin-cs** [comment]
CVC4 and the theory do not have this function for the same reason -- it's not a function.  A floating-point NaN has multiple bit-vector representations, so `fp.to_ieee_bv` could return multiple things.  Z3's implementation returns one of them but actual implementations vary and one of the aims of the theory was to focus on IEEE-754 rather than x86 or ARM or...

The following should is one work around.

```
(declare-fun my_fp_to_ieee_bv_32 (Float32) (_ BitVec 32))
(assert (forall ((Float32 f)) (= (to_fp (my_fp_to_ieee_bv_32 f)) f))
```

Out of interest, what extra functionality are you adding?  There have been a number of requests for additions to the theory and SMT-LIB 3.0 might make it easier to do so.

**Comment by sree314** [comment]
Thanks, the presence of the forall causes issues especially producing models. This works in CVC4 (though it returns "unknown" for check-sat) but I'm able to extract a model:

```
(set-logic ALL)
(set-option :produce-models true)
(declare-fun my_fp_to_ieee_bv_32 (Float32) (_ BitVec 32))
(assert (forall ((f Float32)) (= ((_ to_fp 8 24) (my_fp_to_ieee_bv_32 f)) f)))
(check-sat)
(get-value (my_fp_to_ieee_bv_32 (_ -zero 8 24)))
```

Z3 doesn't finish, however, but I guess I could workaround that as well.

The ability to produce models is important to us because we are validating against an implementation that can only be exhaustively tested. FWIW, the implementation does not preserve NaN payloads either.

We're specifying table-based implementations of the elementary math functions -- sin, cos, etc. These tend to be implemented in hardware using [floating-point adds and multiplies](https://www.computer.org/csdl/proceedings-article/arith/1991/00145565/12OmNCgrD94) to evaluate a polynomial. The coefficients of the polynomial are loaded from hardware tables that are indexed using bits of the significand.  So the ability to "access" the bits of the significand is necessary to index into the coefficient tables. Implementing a C function like `ilogbf` would also require this ability.

We could go bit-vectors all the way, but we'd much rather prefer using the floating point theory.

(Unrelated to this, and I could open a separate issue: will the FP theory in SMT-LIB 3 support -NaN?)

**Comment by martin-cs** [comment]
You may need a trigger on the quantifier as it only needs to be instantiated for calls to `(my_fp_to_ieee_bv_32 f)` or you could just manually instantiate it.

Handling of NaN payloads in implementations is ... varied and patchy.  It is one of the reasons we formalise a step above bit-vectors so we don't have to take a position on this.

Math functions : very interesting.  I have a bunch of work on this that has been delayed by COVID and other factors.  I am happy to chat about it elsewhere.  I am still unsure where the best place to implement these models is; in the analyser's models of the math functions, as SMT generated by the analyzer or in the SMT solver with suitable extensions to the theory.  Regardless; yes, you do need primitives for this.  Would a "remainder mod 2^{1- n}*pi" operator make your life easier?

-NaN : I wouldn't open an issue here because it is an SMT-LIB issue, rather than a CVC4 issue.  I understand the desire for this but it would require a significant rework of the foundations of the semantics and it is not clear to me if it would even be viable to do so.  I also don't think IEEE-754 fixes what happens to the sign bits of a NaN on operation : is -NaN + NaN = NaN or -NaN?

**Comment by sree314** [comment]
Thank you for the pointer to triggers -- I had to look them up, and I'm still reading up on related stuff.

However, triggers/patterns didn't help in my toy examples, so I decided to take a realistic example and see what they could achieve. The good news is that for scenarios where we expect an `unsat` result, the `forall` formulation works very well in both Z3 and CVC4, with and _without_ patterns. For `sat` results, though, Z3's `fp.to_ieee_bv` is more predictable (and faster).

In the gists linked below, the definition of `my_fp_ieee_bv` is changed (these are not minimal examples, apologies in advance):

## Verification Examples

1. [Using Z3's `fp.to_ieee_bv`](https://gist.github.com/sree314/90fbbe7d7d668e37fdfd3046131d15d9)
2. [Using `forall` with no trigger/pattern](https://gist.github.com/sree314/80a52e2ce5539c7d6805c4ac867db2ca)
3. [Using `forall` with a trigger/pattern](https://gist.github.com/sree314/a613c1c98dd4d633efa4df5d0fadb0d8)

In the above examples, the solvers return `unsat` reasonably quickly, but if you trigger a non-`unsat` result by removing the `(assert (= s3_sass ((_ zero_extend 31) s3)))` constraint, then Z3 is still fast when I use `fp.to_ieee_bv`, but doesn't finish using the trigger. CVC4 returns `unknown` when the constraint is removed.

Based on these results, I think having something like Z3's `fp.to_ieee_bv` in CVC4 is valuable.

## Model Finding Examples

1. [Using Z3's `fp.to_ieee_bv`](https://gist.github.com/sree314/782aa8e3aeafc082c184f011b0b96fb0)
2. [Using `forall` with no trigger/pattern](https://gist.github.com/sree314/5efb0be6c75a2ee8497e6bfcb02a47ea)
3. [Using `forall` with a trigger/pattern](https://gist.github.com/sree314/fe3d9cdae2f7e3d86f77275c6aadf04f)

# Math Functions

I didn't understand the remainder mod 2^{1-n}*pi operator, but I may have misled you by listing only cos and sin. We're also interested in reciprocal, square root, logarithm and exponential. Let me whip up a reciprocal implementation and share it.

# -NaN

Sure, I'm hoping SMT-LIB 3 can keep this in mind. IEEE-754-2019 doesn't usually mandate the sign of results when one of the operands is a NaN (Section 6.3) which says:

> When either an input or result is a NaN, this standard does not interpret the sign of a NaN. However,
> operations on bit strings — copy, negate, abs, copySign — specify the sign bit of a NaN result, sometimes
> based upon the sign bit of a NaN operand.

The reason this complicates issues is that it is possible to implement these functions completely using bitvectors, leading to spurious verification errors. Here's a [minimal example of copysign](https://gist.github.com/sree314/c16124d9e876b8d1fb81167bc7140b40), for example, which is inspired from a real machine. In this example, the bitvector result (`r2`) correctly copies the sign from the -NaN bitvector representation, but the FP theory version (`r1`) cannot.
