### ISSUE TITLE
(check-unsat-cores) Fatal faliure at src/theory/fp/theory_fp.cpp:819

### ISSUE THREAD

**Issue by muchang** [CVC4/CVC4#5734]
```
[539] % cvc4 --check-unsat-cores small.smt2
Fatal failure within void CVC4::theory::fp::TheoryFp::registerTerm(CVC4::TNode) at src/theory/fp/theory_fp.cpp:819
Check failure

 k != kind::FLOATINGPOINT_TO_FP_GENERIC && k != kind::FLOATINGPOINT_SUB && k != kind::FLOATINGPOINT_EQ && k != kind::FLOATINGPOINT_GEQ && k != kind::FLOATINGPOINT_GT

Aborted
[540] % 
[540] % cat small.smt2
(set-logic QF_FP)
(declare-fun a () RoundingMode)
(declare-fun b () (_ FloatingPoint 8 24))
(assert (= b (fp.add a b (fp.add a ((_ to_fp 8 24) a ((_ to_fp 8 24) a 0)) b))))
(check-sat)
[541] % 
```
Commit: e0dfc0a

**Comment by martin-cs** [comment]
Hi @muchang 

As ever we are thankful for all bug reports but please let me draw your attention back to the fuzzing guidelines we agreed with your group a few months back:

https://github.com/CVC4/CVC4/wiki/Fuzzing-CVC4

Unless I am mistaken, today you submitted 9 issues, 2 of which are priority 1 refutational soundness bugs and the rest are priority 4 crashes.

Please can you try to follow the guidelines?  Investigating and fixing these issues takes considerably more human effort than finding them via fuzzing.  I appreciate that you have paper deadlines coming up and that us working on these helps strengthen your submission but please understand that we also have our own papers to work on and many other demands on our time.  Please bear with us while we make the time to work on these issues.

**Comment by muchang** [comment]
Thanks, @martin-cs. 

I am sorry for overrunning our bug reports budget. I was considering to use the budgets of the last few weeks when we did not report the bugs, so I reported 9 issues. I will rigorously obey the rule of 3 bugs each week in the future.

We also highly appreciate your and your team's effort in fixing the bugs. We are not reporting the bugs for enhancing the strength of our papers, but sincerely would like to help the community build nice solvers, like CVC4, and contribute our effort on finding bugs. We just shared what we have found in the issue tracker. Therefore, it is totally okay for you and your team to take your time, and it is no need to fix the issues in a hurry. You and your team's work is also quite meaningful to this community, thus I appreciate your time on your own work as well. Wish you everything goes well and have good luck!

**Comment by martin-cs** [comment]
Thank you for your kind words and consideration.  If your primary motivation is improving solvers, may I suggest that there are more efficient uses of your time and expertise.  Almost every solver would benefit from:

- More developers, particularly for helping fix the kind of code quality issues you have been raising.
- Better CI : regression testing, particularly performance regression testing and coverage checking.  There are some really interesting research challenges in terms of finding minimal sets of benchmarks required to detect performance regression or changes in test coverage.
- Better documentation, particularly for helping new developers rapidly understand the architecture of the system.
- Improvements in proof generation and checking give us a route to eliminate the risk of unsound results.  Where is the tool that takes a SAT formula and model and produces a single SMT-LIB file that can be used to cross check the model using other solvers?

At the community / multi-solver level:

- Previous work on model based testers have detected a large numbers of high-quality correctness issues.  @timothy-king and @aniemetz have a working system but it needs to be extended to new theories and widely deployed.
- SMT-LIB always needs new benchmarks, simply co-ordinating and curating the collection of these from recent publications would be a massive benefit to the community.
- There are delta-debuggers for SMT-LIB, again, these need improvement and extension.
- Fuzzing to find minimal differences to SMT-LIB benchmarks that trigger correctness issues or even large performance deltas would be super useful and highly relevant.  The randomisation used in SMT-COMP uncovers issues like this most years so this should be low-hanging fruit.
- Rewrite rules are hard to test and we believe that there aren't rewrite loops but there is little tooling here.
- There are no glass-box testing tools for SMT solvers.  Most solvers output a large amount of tracing and diagnostic information which seems like a great starting point for some kind of machine learning or fuzzing approaches.
- One fuzzing team are doing a great job at producing micro-benchmarks that show performance discrepancies between solvers.  The problem is that analyzing why things run solver than they should is pretty much a black art and very time intensive.  They are producing insightful benchmarks faster than we can make sense of them.  Any kind of tooling to help understand why solvers take a different amount of time to solve a problem could make a huge difference to the efficiency of solver development.

**Comment by muchang** [comment]
Thank you very much for your nice and insightful suggestions! They are quite helpful. 

Yes, besides finding bugs, we are also exploring other ways to help improve the solvers. Your suggestions present a nice roadmap. In fact, we have been considering some of the points. Hope some nice ideas can come and work out.

**Comment by martin-cs** [comment]
Sure.  We are always happy to discuss ideas and approaches.  For many of the ideas above there are team members who have code or experience in doing things manually.  Also note that the different theories (and different solvers) are at different levels of maturity so what is useful can vary theory to theory.

**Comment by aniemetz** [comment]
This issue does not need `--check-unsat-core` to trigger.

@ajreynol This seems to be fixed with https://github.com/CVC4/CVC4/commit/4cd2d73366aba081a38900ddc2f4f172ce9ed2f8. Does this sound reasonable to you?

**Comment by ajreynol** [comment]
Yes, that commit would be related to fixing this bug.  Can we add it as a regression and close this?

**Comment by aniemetz** [comment]
Added regression test in #6480.
