### ISSUE TITLE
Question about push/pop contexts and formula checking

### ISSUE THREAD

**Issue by 0152la** [CVC4/CVC4#5962]
I found a behaviour in CVC4 (commit f1c384dff82bffa56b9cf9ba18ec1f35aa529b12) which I find counter-intuitive. Suppose there are two boolean formulas, *f* and *g*, and a query of the form:

```
(set-logic QF_NIA)
; sequence of (declare-const _ Int)
(push)
(assert f)
(check-sat)
(pop)
(push)
(assert g)
(check-sat)
(pop)
```

I would expect that the two `check-sat` calls to happen in completely disjoint contexts. However, running the above query, produces `unsat,unknown`, but if I comment out the check corresponding to *f*, then the tools returns `sat`. Is there some intuition behind why a check in its own push-pop context might affect a subsequent check in another push-pop context, or is this a potential CVC4 issue?

Furthermore, I would like to note that changing the logic to `ALL` yields `unsat,sat`.

**Comment by nafur** [comment]
In general, the two check-sat calls **may** be executed in completely different contexts here, pretty much like you would call the solver two times. While most state is and must be cleared when processing a pop, a solver can still retain some state which may change future behavior: the more obvious ones being caches (in preprocessing, rewriting, theory solving, ...), but also more subtle ones like changing node ids (if `f` and `g` share subterms, the relative order of terms in `g` may change, which influences the order in which certain things are processed).

Note that `QF_NIA` is undecidable and in some sense you need to be lucky to find sat/unsat instead of unknown here, and any of the above data could make this difference.
Changing the logic somtimes changes which approaches are employed for solving.

**Comment by 0152la** [comment]
That makes sense of how internal state can affect solver efficiency, even if things on the surface might seem completely independent. Thanks for shedding some light on this matter.

**Comment by ajreynol** [comment]
One other note: you can use the option `--nl-ext-tplanes` if you prefer the solver to "try harder" instead of answering unknown for problems with non-linear integer arithmetic.
