### ISSUE TITLE
Fatal failure cvc4 1.8 at type_checker_template.cpp:51 with --finite-model-find

### ISSUE THREAD

**Issue by robby-phd** [CVC4/CVC4#6100]
**Describe the bug**

cvc4 1.8 with `--finite-model-find` fails for the attached input.

[cvc4-bug.smt2.gz](https://github.com/CVC4/CVC4/files/6112170/cvc4-bug.smt2.gz)

```bash
$ cvc4 cvc4-bug.smt2
unknown
$ cvc4 --finite-model-find cvc4-bug.smt2
Fatal failure within static CVC4::TypeNode CVC4::expr::TypeChecker::computeType(CVC4::NodeManager *, CVC4::TNode, bool) at /Users/noetzli/repos/CVC4_release/src/expr/type_checker_template.cpp:51
Unhandled case encounteredNULL
```

**Command line arguments**: --finite-model-find
**CVC4 version/commit**: [1.8 release binary [git master 3bc4a541]](https://github.com/CVC4/CVC4/releases/download/1.8/cvc4-1.8-macos-opt)
**Operating system**: macOS 11.2.3

**Comment by ajreynol** [comment]
Hi Robby,

Thanks for the benchmark.  

This is due to the combination of arrays and finite model finding.  There is a sort (Array Int A) where the uninterpreted sort A is assigned cardinality one. This makes the sort (Array Int A) have cardinality one, but certain parts of the code are assuming this is an infinite type. This makes our model builder run out of values, leading to the error.

The solution will be to ensure that we properly handle theory combination for finite model finding + arrays.  Note this issue may be related: https://github.com/CVC4/CVC4/issues/4260

FYI @barrettcw .
